// Code generated by ent, DO NOT EDIT.

package activequiz

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the activequiz type in the database.
	Label = "active_quiz"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuestionID holds the string denoting the question_id field in the database.
	FieldQuestionID = "question_id"
	// FieldMessageID holds the string denoting the message_id field in the database.
	FieldMessageID = "message_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldGuildID holds the string denoting the guild_id field in the database.
	FieldGuildID = "guild_id"
	// FieldShuffle holds the string denoting the shuffle field in the database.
	FieldShuffle = "shuffle"
	// FieldLaunchedAt holds the string denoting the launched_at field in the database.
	FieldLaunchedAt = "launched_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeQuestion holds the string denoting the question edge name in mutations.
	EdgeQuestion = "question"
	// EdgeUserAnswers holds the string denoting the user_answers edge name in mutations.
	EdgeUserAnswers = "user_answers"
	// Table holds the table name of the activequiz in the database.
	Table = "active_quizs"
	// QuestionTable is the table that holds the question relation/edge.
	QuestionTable = "active_quizs"
	// QuestionInverseTable is the table name for the QuizQuestion entity.
	// It exists in this package in order to avoid circular dependency with the "quizquestion" package.
	QuestionInverseTable = "quiz_questions"
	// QuestionColumn is the table column denoting the question relation/edge.
	QuestionColumn = "question_id"
	// UserAnswersTable is the table that holds the user_answers relation/edge.
	UserAnswersTable = "quiz_user_answers"
	// UserAnswersInverseTable is the table name for the QuizUserAnswer entity.
	// It exists in this package in order to avoid circular dependency with the "quizuseranswer" package.
	UserAnswersInverseTable = "quiz_user_answers"
	// UserAnswersColumn is the table column denoting the user_answers relation/edge.
	UserAnswersColumn = "active_quiz_id"
)

// Columns holds all SQL columns for activequiz fields.
var Columns = []string{
	FieldID,
	FieldQuestionID,
	FieldMessageID,
	FieldChannelID,
	FieldGuildID,
	FieldShuffle,
	FieldLaunchedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ShuffleValidator is a validator for the "shuffle" field. It is called by the builders before save.
	ShuffleValidator func(string) error
	// DefaultLaunchedAt holds the default value on creation for the "launched_at" field.
	DefaultLaunchedAt func() time.Time
)

// OrderOption defines the ordering options for the ActiveQuiz queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByQuestionID orders the results by the question_id field.
func ByQuestionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestionID, opts...).ToFunc()
}

// ByMessageID orders the results by the message_id field.
func ByMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByGuildID orders the results by the guild_id field.
func ByGuildID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGuildID, opts...).ToFunc()
}

// ByShuffle orders the results by the shuffle field.
func ByShuffle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShuffle, opts...).ToFunc()
}

// ByLaunchedAt orders the results by the launched_at field.
func ByLaunchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLaunchedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByQuestionField orders the results by question field.
func ByQuestionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuestionStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserAnswersCount orders the results by user_answers count.
func ByUserAnswersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserAnswersStep(), opts...)
	}
}

// ByUserAnswers orders the results by user_answers terms.
func ByUserAnswers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserAnswersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newQuestionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuestionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, QuestionTable, QuestionColumn),
	)
}
func newUserAnswersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserAnswersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserAnswersTable, UserAnswersColumn),
	)
}
