// Code generated by ent, DO NOT EDIT.

package quizanswer

import (
	"Eve/internal/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldContainsFold(FieldID, id))
}

// AnswerText applies equality check predicate on the "answer_text" field. It's identical to AnswerTextEQ.
func AnswerText(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEQ(FieldAnswerText, v))
}

// IsValid applies equality check predicate on the "is_valid" field. It's identical to IsValidEQ.
func IsValid(v bool) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEQ(FieldIsValid, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEQ(FieldUpdatedAt, v))
}

// AnswerTextEQ applies the EQ predicate on the "answer_text" field.
func AnswerTextEQ(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEQ(FieldAnswerText, v))
}

// AnswerTextNEQ applies the NEQ predicate on the "answer_text" field.
func AnswerTextNEQ(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldNEQ(FieldAnswerText, v))
}

// AnswerTextIn applies the In predicate on the "answer_text" field.
func AnswerTextIn(vs ...string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldIn(FieldAnswerText, vs...))
}

// AnswerTextNotIn applies the NotIn predicate on the "answer_text" field.
func AnswerTextNotIn(vs ...string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldNotIn(FieldAnswerText, vs...))
}

// AnswerTextGT applies the GT predicate on the "answer_text" field.
func AnswerTextGT(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldGT(FieldAnswerText, v))
}

// AnswerTextGTE applies the GTE predicate on the "answer_text" field.
func AnswerTextGTE(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldGTE(FieldAnswerText, v))
}

// AnswerTextLT applies the LT predicate on the "answer_text" field.
func AnswerTextLT(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldLT(FieldAnswerText, v))
}

// AnswerTextLTE applies the LTE predicate on the "answer_text" field.
func AnswerTextLTE(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldLTE(FieldAnswerText, v))
}

// AnswerTextContains applies the Contains predicate on the "answer_text" field.
func AnswerTextContains(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldContains(FieldAnswerText, v))
}

// AnswerTextHasPrefix applies the HasPrefix predicate on the "answer_text" field.
func AnswerTextHasPrefix(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldHasPrefix(FieldAnswerText, v))
}

// AnswerTextHasSuffix applies the HasSuffix predicate on the "answer_text" field.
func AnswerTextHasSuffix(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldHasSuffix(FieldAnswerText, v))
}

// AnswerTextEqualFold applies the EqualFold predicate on the "answer_text" field.
func AnswerTextEqualFold(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEqualFold(FieldAnswerText, v))
}

// AnswerTextContainsFold applies the ContainsFold predicate on the "answer_text" field.
func AnswerTextContainsFold(v string) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldContainsFold(FieldAnswerText, v))
}

// IsValidEQ applies the EQ predicate on the "is_valid" field.
func IsValidEQ(v bool) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEQ(FieldIsValid, v))
}

// IsValidNEQ applies the NEQ predicate on the "is_valid" field.
func IsValidNEQ(v bool) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldNEQ(FieldIsValid, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasQuestion applies the HasEdge predicate on the "question" edge.
func HasQuestion() predicate.QuizAnswer {
	return predicate.QuizAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuestionTable, QuestionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestionWith applies the HasEdge predicate on the "question" edge with a given conditions (other predicates).
func HasQuestionWith(preds ...predicate.QuizQuestion) predicate.QuizAnswer {
	return predicate.QuizAnswer(func(s *sql.Selector) {
		step := newQuestionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserAnswers applies the HasEdge predicate on the "user_answers" edge.
func HasUserAnswers() predicate.QuizAnswer {
	return predicate.QuizAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserAnswersTable, UserAnswersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserAnswersWith applies the HasEdge predicate on the "user_answers" edge with a given conditions (other predicates).
func HasUserAnswersWith(preds ...predicate.QuizUserAnswer) predicate.QuizAnswer {
	return predicate.QuizAnswer(func(s *sql.Selector) {
		step := newUserAnswersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuizAnswer) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuizAnswer) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuizAnswer) predicate.QuizAnswer {
	return predicate.QuizAnswer(sql.NotPredicates(p))
}
