// Code generated by ent, DO NOT EDIT.

package lotogame

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the lotogame type in the database.
	Label = "loto_game"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGuildID holds the string denoting the guild_id field in the database.
	FieldGuildID = "guild_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldTicketPrice holds the string denoting the ticket_price field in the database.
	FieldTicketPrice = "ticket_price"
	// FieldCooldownMinutes holds the string denoting the cooldown_minutes field in the database.
	FieldCooldownMinutes = "cooldown_minutes"
	// FieldMaxTicketsPerPurchase holds the string denoting the max_tickets_per_purchase field in the database.
	FieldMaxTicketsPerPurchase = "max_tickets_per_purchase"
	// FieldMessageID holds the string denoting the message_id field in the database.
	FieldMessageID = "message_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePlayers holds the string denoting the players edge name in mutations.
	EdgePlayers = "players"
	// EdgeTickets holds the string denoting the tickets edge name in mutations.
	EdgeTickets = "tickets"
	// EdgePrizes holds the string denoting the prizes edge name in mutations.
	EdgePrizes = "prizes"
	// Table holds the table name of the lotogame in the database.
	Table = "loto_games"
	// PlayersTable is the table that holds the players relation/edge.
	PlayersTable = "loto_players"
	// PlayersInverseTable is the table name for the LotoPlayer entity.
	// It exists in this package in order to avoid circular dependency with the "lotoplayer" package.
	PlayersInverseTable = "loto_players"
	// PlayersColumn is the table column denoting the players relation/edge.
	PlayersColumn = "game_id"
	// TicketsTable is the table that holds the tickets relation/edge.
	TicketsTable = "loto_tickets"
	// TicketsInverseTable is the table name for the LotoTicket entity.
	// It exists in this package in order to avoid circular dependency with the "lototicket" package.
	TicketsInverseTable = "loto_tickets"
	// TicketsColumn is the table column denoting the tickets relation/edge.
	TicketsColumn = "game_id"
	// PrizesTable is the table that holds the prizes relation/edge.
	PrizesTable = "loto_prizes"
	// PrizesInverseTable is the table name for the LotoPrize entity.
	// It exists in this package in order to avoid circular dependency with the "lotoprize" package.
	PrizesInverseTable = "loto_prizes"
	// PrizesColumn is the table column denoting the prizes relation/edge.
	PrizesColumn = "game_id"
)

// Columns holds all SQL columns for lotogame fields.
var Columns = []string{
	FieldID,
	FieldGuildID,
	FieldName,
	FieldActive,
	FieldTicketPrice,
	FieldCooldownMinutes,
	FieldMaxTicketsPerPurchase,
	FieldMessageID,
	FieldChannelID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultTicketPrice holds the default value on creation for the "ticket_price" field.
	DefaultTicketPrice int
	// DefaultCooldownMinutes holds the default value on creation for the "cooldown_minutes" field.
	DefaultCooldownMinutes int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotoGame queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGuildID orders the results by the guild_id field.
func ByGuildID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGuildID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByTicketPrice orders the results by the ticket_price field.
func ByTicketPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketPrice, opts...).ToFunc()
}

// ByCooldownMinutes orders the results by the cooldown_minutes field.
func ByCooldownMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownMinutes, opts...).ToFunc()
}

// ByMaxTicketsPerPurchase orders the results by the max_tickets_per_purchase field.
func ByMaxTicketsPerPurchase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxTicketsPerPurchase, opts...).ToFunc()
}

// ByMessageID orders the results by the message_id field.
func ByMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPlayersCount orders the results by players count.
func ByPlayersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlayersStep(), opts...)
	}
}

// ByPlayers orders the results by players terms.
func ByPlayers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlayersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTicketsCount orders the results by tickets count.
func ByTicketsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTicketsStep(), opts...)
	}
}

// ByTickets orders the results by tickets terms.
func ByTickets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTicketsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPrizesCount orders the results by prizes count.
func ByPrizesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPrizesStep(), opts...)
	}
}

// ByPrizes orders the results by prizes terms.
func ByPrizes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrizesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPlayersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlayersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PlayersTable, PlayersColumn),
	)
}
func newTicketsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TicketsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TicketsTable, TicketsColumn),
	)
}
func newPrizesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrizesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PrizesTable, PrizesColumn),
	)
}
