-- Drop the legacy quiz schema (Quiz / QuizAnswer schemas were removed; QuizQuestion
-- and QuizUserAnswer were rewritten with an incompatible column layout). These tables
-- carry no production data yet, so they are recreated from scratch below rather than
-- reshaped in place.
-- Drop "quiz_user_answers" table
DROP TABLE IF EXISTS "quiz_user_answers";
-- Drop "quiz_answers" table
DROP TABLE IF EXISTS "quiz_answers";
-- Drop "quiz_questions" table
DROP TABLE IF EXISTS "quiz_questions";
-- Drop "quizs" table
DROP TABLE IF EXISTS "quizs";
-- Create "active_motus" table
CREATE TABLE "active_motus" ("id" character varying NOT NULL, "message_id" character varying NOT NULL, "channel_id" character varying NOT NULL, "guild_id" character varying NOT NULL, "word" character varying NOT NULL, "attempts" jsonb NOT NULL, "state" character varying NOT NULL DEFAULT 'playing', "started_by" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "expires_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "active_motus_message_id_key" to table: "active_motus"
CREATE UNIQUE INDEX "active_motus_message_id_key" ON "active_motus" ("message_id");
-- Create "mp_threads" table
CREATE TABLE "mp_threads" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" character varying NOT NULL, "thread_id" character varying NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "mp_threads_user_id_key" to table: "mp_threads"
CREATE UNIQUE INDEX "mp_threads_user_id_key" ON "mp_threads" ("user_id");
-- Create index "mp_threads_thread_id_key" to table: "mp_threads"
CREATE UNIQUE INDEX "mp_threads_thread_id_key" ON "mp_threads" ("thread_id");
-- Create "quiz_questions" table
CREATE TABLE "quiz_questions" ("id" character varying NOT NULL, "question" character varying NOT NULL, "good_answer" character varying NOT NULL, "bad_answer_1" character varying NOT NULL, "bad_answer_2" character varying NOT NULL, "bad_answer_3" character varying NOT NULL, "category" character varying NOT NULL, "difficulty" character varying NOT NULL, "author_id" character varying NULL, "guild_id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "last_used_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "quiz_questions_question_key" to table: "quiz_questions"
CREATE UNIQUE INDEX "quiz_questions_question_key" ON "quiz_questions" ("question");
-- Create "quiz_stats" table
CREATE TABLE "quiz_stats" ("id" character varying NOT NULL, "user_id" character varying NOT NULL, "good_answers" bigint NOT NULL DEFAULT 0, "bad_answers" bigint NOT NULL DEFAULT 0, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "quiz_stats_user_id_key" to table: "quiz_stats"
CREATE UNIQUE INDEX "quiz_stats_user_id_key" ON "quiz_stats" ("user_id");
-- Create "streams" table
CREATE TABLE "streams" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "guild_id" character varying NOT NULL, "channel_id" character varying NOT NULL, "role_id" character varying NULL, "twitch_user_id" character varying NOT NULL, "twitch_login" character varying NOT NULL, "message_id" character varying NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "stream_guild_id_twitch_user_id" to table: "streams"
CREATE UNIQUE INDEX "stream_guild_id_twitch_user_id" ON "streams" ("guild_id", "twitch_user_id");
-- Create "active_quizs" table
CREATE TABLE "active_quizs" ("id" character varying NOT NULL, "message_id" character varying NOT NULL, "channel_id" character varying NOT NULL, "guild_id" character varying NOT NULL, "shuffle" character varying NOT NULL, "launched_at" timestamptz NOT NULL, "expires_at" timestamptz NOT NULL, "question_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "active_quizs_quiz_questions_active_quizzes" FOREIGN KEY ("question_id") REFERENCES "quiz_questions" ("id") ON DELETE CASCADE);
-- Create index "active_quizs_message_id_key" to table: "active_quizs"
CREATE UNIQUE INDEX "active_quizs_message_id_key" ON "active_quizs" ("message_id");
-- Create "loto_games" table
CREATE TABLE "loto_games" ("id" character varying NOT NULL, "guild_id" character varying NOT NULL, "name" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, "ticket_price" bigint NOT NULL DEFAULT 500, "cooldown_minutes" bigint NOT NULL DEFAULT 0, "max_tickets_per_purchase" bigint NULL, "message_id" character varying NULL, "channel_id" character varying NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "lotogame_guild_id_active" to table: "loto_games"
CREATE INDEX "lotogame_guild_id_active" ON "loto_games" ("guild_id", "active");
-- Create "loto_players" table
CREATE TABLE "loto_players" ("id" character varying NOT NULL, "name" character varying NOT NULL, "last_play" timestamptz NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "game_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "loto_players_loto_games_players" FOREIGN KEY ("game_id") REFERENCES "loto_games" ("id") ON DELETE CASCADE);
-- Create index "lotoplayer_game_id_name" to table: "loto_players"
CREATE UNIQUE INDEX "lotoplayer_game_id_name" ON "loto_players" ("game_id", "name");
-- Create "loto_prizes" table
CREATE TABLE "loto_prizes" ("id" character varying NOT NULL, "label" character varying NOT NULL, "position" bigint NOT NULL, "winning_ticket_number" bigint NULL, "drawn_at" timestamptz NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "game_id" character varying NOT NULL, "winner_player_id" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "loto_prizes_loto_games_prizes" FOREIGN KEY ("game_id") REFERENCES "loto_games" ("id") ON DELETE CASCADE, CONSTRAINT "loto_prizes_loto_players_won_prizes" FOREIGN KEY ("winner_player_id") REFERENCES "loto_players" ("id") ON DELETE SET NULL);
-- Create index "lotoprize_game_id_position" to table: "loto_prizes"
CREATE UNIQUE INDEX "lotoprize_game_id_position" ON "loto_prizes" ("game_id", "position");
-- Create "loto_tickets" table
CREATE TABLE "loto_tickets" ("id" character varying NOT NULL, "seller_id" character varying NOT NULL, "number" bigint NOT NULL, "created_at" timestamptz NOT NULL, "game_id" character varying NOT NULL, "player_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "loto_tickets_loto_games_tickets" FOREIGN KEY ("game_id") REFERENCES "loto_games" ("id") ON DELETE CASCADE, CONSTRAINT "loto_tickets_loto_players_tickets" FOREIGN KEY ("player_id") REFERENCES "loto_players" ("id") ON DELETE CASCADE);
-- Create index "lototicket_game_id_number" to table: "loto_tickets"
CREATE UNIQUE INDEX "lototicket_game_id_number" ON "loto_tickets" ("game_id", "number");
-- Create index "lototicket_player_id" to table: "loto_tickets"
CREATE INDEX "lototicket_player_id" ON "loto_tickets" ("player_id");
-- Create "quiz_user_answers" table
CREATE TABLE "quiz_user_answers" ("id" character varying NOT NULL, "user_id" character varying NOT NULL, "correct" boolean NOT NULL DEFAULT false, "answered_at" timestamptz NOT NULL, "active_quiz_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "quiz_user_answers_active_quizs_user_answers" FOREIGN KEY ("active_quiz_id") REFERENCES "active_quizs" ("id") ON DELETE CASCADE);
-- Create index "quizuseranswer_active_quiz_id_user_id" to table: "quiz_user_answers"
CREATE UNIQUE INDEX "quizuseranswer_active_quiz_id_user_id" ON "quiz_user_answers" ("active_quiz_id", "user_id");
