// Code generated by ent, DO NOT EDIT.

package quizuseranswer

import (
	"Eve/internal/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldEQ(FieldUserID, v))
}

// AnsweredAt applies equality check predicate on the "answered_at" field. It's identical to AnsweredAtEQ.
func AnsweredAt(v time.Time) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldEQ(FieldAnsweredAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldContainsFold(FieldUserID, v))
}

// AnsweredAtEQ applies the EQ predicate on the "answered_at" field.
func AnsweredAtEQ(v time.Time) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldEQ(FieldAnsweredAt, v))
}

// AnsweredAtNEQ applies the NEQ predicate on the "answered_at" field.
func AnsweredAtNEQ(v time.Time) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldNEQ(FieldAnsweredAt, v))
}

// AnsweredAtIn applies the In predicate on the "answered_at" field.
func AnsweredAtIn(vs ...time.Time) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldIn(FieldAnsweredAt, vs...))
}

// AnsweredAtNotIn applies the NotIn predicate on the "answered_at" field.
func AnsweredAtNotIn(vs ...time.Time) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldNotIn(FieldAnsweredAt, vs...))
}

// AnsweredAtGT applies the GT predicate on the "answered_at" field.
func AnsweredAtGT(v time.Time) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldGT(FieldAnsweredAt, v))
}

// AnsweredAtGTE applies the GTE predicate on the "answered_at" field.
func AnsweredAtGTE(v time.Time) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldGTE(FieldAnsweredAt, v))
}

// AnsweredAtLT applies the LT predicate on the "answered_at" field.
func AnsweredAtLT(v time.Time) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldLT(FieldAnsweredAt, v))
}

// AnsweredAtLTE applies the LTE predicate on the "answered_at" field.
func AnsweredAtLTE(v time.Time) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.FieldLTE(FieldAnsweredAt, v))
}

// HasQuestion applies the HasEdge predicate on the "question" edge.
func HasQuestion() predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuestionTable, QuestionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestionWith applies the HasEdge predicate on the "question" edge with a given conditions (other predicates).
func HasQuestionWith(preds ...predicate.QuizQuestion) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(func(s *sql.Selector) {
		step := newQuestionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnswer applies the HasEdge predicate on the "answer" edge.
func HasAnswer() predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AnswerTable, AnswerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnswerWith applies the HasEdge predicate on the "answer" edge with a given conditions (other predicates).
func HasAnswerWith(preds ...predicate.QuizAnswer) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(func(s *sql.Selector) {
		step := newAnswerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuizUserAnswer) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuizUserAnswer) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuizUserAnswer) predicate.QuizUserAnswer {
	return predicate.QuizUserAnswer(sql.NotPredicates(p))
}
