// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/activemotus"
	"Eve/internal/database/tables"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ActiveMotusCreate is the builder for creating a ActiveMotus entity.
type ActiveMotusCreate struct {
	config
	mutation *ActiveMotusMutation
	hooks    []Hook
}

// SetMessageID sets the "message_id" field.
func (_c *ActiveMotusCreate) SetMessageID(v string) *ActiveMotusCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ActiveMotusCreate) SetChannelID(v string) *ActiveMotusCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetGuildID sets the "guild_id" field.
func (_c *ActiveMotusCreate) SetGuildID(v string) *ActiveMotusCreate {
	_c.mutation.SetGuildID(v)
	return _c
}

// SetWord sets the "word" field.
func (_c *ActiveMotusCreate) SetWord(v string) *ActiveMotusCreate {
	_c.mutation.SetWord(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *ActiveMotusCreate) SetAttempts(v []tables.MotusAttempt) *ActiveMotusCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetState sets the "state" field.
func (_c *ActiveMotusCreate) SetState(v string) *ActiveMotusCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *ActiveMotusCreate) SetNillableState(v *string) *ActiveMotusCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetStartedBy sets the "started_by" field.
func (_c *ActiveMotusCreate) SetStartedBy(v string) *ActiveMotusCreate {
	_c.mutation.SetStartedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ActiveMotusCreate) SetCreatedAt(v time.Time) *ActiveMotusCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ActiveMotusCreate) SetNillableCreatedAt(v *time.Time) *ActiveMotusCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ActiveMotusCreate) SetUpdatedAt(v time.Time) *ActiveMotusCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ActiveMotusCreate) SetNillableUpdatedAt(v *time.Time) *ActiveMotusCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ActiveMotusCreate) SetExpiresAt(v time.Time) *ActiveMotusCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ActiveMotusCreate) SetID(v string) *ActiveMotusCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ActiveMotusMutation object of the builder.
func (_c *ActiveMotusCreate) Mutation() *ActiveMotusMutation {
	return _c.mutation
}

// Save creates the ActiveMotus in the database.
func (_c *ActiveMotusCreate) Save(ctx context.Context) (*ActiveMotus, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActiveMotusCreate) SaveX(ctx context.Context) *ActiveMotus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActiveMotusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActiveMotusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActiveMotusCreate) defaults() {
	if _, ok := _c.mutation.Attempts(); !ok {
		v := activemotus.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := activemotus.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := activemotus.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := activemotus.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActiveMotusCreate) check() error {
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "ActiveMotus.message_id"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ActiveMotus.channel_id"`)}
	}
	if _, ok := _c.mutation.GuildID(); !ok {
		return &ValidationError{Name: "guild_id", err: errors.New(`ent: missing required field "ActiveMotus.guild_id"`)}
	}
	if _, ok := _c.mutation.Word(); !ok {
		return &ValidationError{Name: "word", err: errors.New(`ent: missing required field "ActiveMotus.word"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "ActiveMotus.attempts"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "ActiveMotus.state"`)}
	}
	if _, ok := _c.mutation.StartedBy(); !ok {
		return &ValidationError{Name: "started_by", err: errors.New(`ent: missing required field "ActiveMotus.started_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ActiveMotus.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ActiveMotus.updated_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "ActiveMotus.expires_at"`)}
	}
	return nil
}

func (_c *ActiveMotusCreate) sqlSave(ctx context.Context) (*ActiveMotus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ActiveMotus.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActiveMotusCreate) createSpec() (*ActiveMotus, *sqlgraph.CreateSpec) {
	var (
		_node = &ActiveMotus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(activemotus.Table, sqlgraph.NewFieldSpec(activemotus.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(activemotus.FieldMessageID, field.TypeString, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(activemotus.FieldChannelID, field.TypeString, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.GuildID(); ok {
		_spec.SetField(activemotus.FieldGuildID, field.TypeString, value)
		_node.GuildID = value
	}
	if value, ok := _c.mutation.Word(); ok {
		_spec.SetField(activemotus.FieldWord, field.TypeString, value)
		_node.Word = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(activemotus.FieldAttempts, field.TypeJSON, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(activemotus.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.StartedBy(); ok {
		_spec.SetField(activemotus.FieldStartedBy, field.TypeString, value)
		_node.StartedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(activemotus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(activemotus.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(activemotus.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// ActiveMotusCreateBulk is the builder for creating many ActiveMotus entities in bulk.
type ActiveMotusCreateBulk struct {
	config
	err      error
	builders []*ActiveMotusCreate
}

// Save creates the ActiveMotus entities in the database.
func (_c *ActiveMotusCreateBulk) Save(ctx context.Context) ([]*ActiveMotus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ActiveMotus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActiveMotusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActiveMotusCreateBulk) SaveX(ctx context.Context) []*ActiveMotus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActiveMotusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActiveMotusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
