// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/activequiz"
	"Eve/internal/database/ent/quizquestion"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ActiveQuiz is the model entity for the ActiveQuiz schema.
type ActiveQuiz struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// QuestionID holds the value of the "question_id" field.
	QuestionID string `json:"question_id,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID string `json:"message_id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID string `json:"channel_id,omitempty"`
	// GuildID holds the value of the "guild_id" field.
	GuildID string `json:"guild_id,omitempty"`
	// Shuffle holds the value of the "shuffle" field.
	Shuffle string `json:"shuffle,omitempty"`
	// LaunchedAt holds the value of the "launched_at" field.
	LaunchedAt time.Time `json:"launched_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActiveQuizQuery when eager-loading is set.
	Edges        ActiveQuizEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ActiveQuizEdges holds the relations/edges for other nodes in the graph.
type ActiveQuizEdges struct {
	// Question holds the value of the question edge.
	Question *QuizQuestion `json:"question,omitempty"`
	// UserAnswers holds the value of the user_answers edge.
	UserAnswers []*QuizUserAnswer `json:"user_answers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActiveQuizEdges) QuestionOrErr() (*QuizQuestion, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: quizquestion.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// UserAnswersOrErr returns the UserAnswers value or an error if the edge
// was not loaded in eager-loading.
func (e ActiveQuizEdges) UserAnswersOrErr() ([]*QuizUserAnswer, error) {
	if e.loadedTypes[1] {
		return e.UserAnswers, nil
	}
	return nil, &NotLoadedError{edge: "user_answers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActiveQuiz) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case activequiz.FieldID, activequiz.FieldQuestionID, activequiz.FieldMessageID, activequiz.FieldChannelID, activequiz.FieldGuildID, activequiz.FieldShuffle:
			values[i] = new(sql.NullString)
		case activequiz.FieldLaunchedAt, activequiz.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActiveQuiz fields.
func (_m *ActiveQuiz) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case activequiz.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case activequiz.FieldQuestionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field question_id", values[i])
			} else if value.Valid {
				_m.QuestionID = value.String
			}
		case activequiz.FieldMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = value.String
			}
		case activequiz.FieldChannelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = value.String
			}
		case activequiz.FieldGuildID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guild_id", values[i])
			} else if value.Valid {
				_m.GuildID = value.String
			}
		case activequiz.FieldShuffle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field shuffle", values[i])
			} else if value.Valid {
				_m.Shuffle = value.String
			}
		case activequiz.FieldLaunchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field launched_at", values[i])
			} else if value.Valid {
				_m.LaunchedAt = value.Time
			}
		case activequiz.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ActiveQuiz.
// This includes values selected through modifiers, order, etc.
func (_m *ActiveQuiz) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuestion queries the "question" edge of the ActiveQuiz entity.
func (_m *ActiveQuiz) QueryQuestion() *QuizQuestionQuery {
	return NewActiveQuizClient(_m.config).QueryQuestion(_m)
}

// QueryUserAnswers queries the "user_answers" edge of the ActiveQuiz entity.
func (_m *ActiveQuiz) QueryUserAnswers() *QuizUserAnswerQuery {
	return NewActiveQuizClient(_m.config).QueryUserAnswers(_m)
}

// Update returns a builder for updating this ActiveQuiz.
// Note that you need to call ActiveQuiz.Unwrap() before calling this method if this ActiveQuiz
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ActiveQuiz) Update() *ActiveQuizUpdateOne {
	return NewActiveQuizClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ActiveQuiz entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ActiveQuiz) Unwrap() *ActiveQuiz {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActiveQuiz is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ActiveQuiz) String() string {
	var builder strings.Builder
	builder.WriteString("ActiveQuiz(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("question_id=")
	builder.WriteString(_m.QuestionID)
	builder.WriteString(", ")
	builder.WriteString("message_id=")
	builder.WriteString(_m.MessageID)
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(_m.ChannelID)
	builder.WriteString(", ")
	builder.WriteString("guild_id=")
	builder.WriteString(_m.GuildID)
	builder.WriteString(", ")
	builder.WriteString("shuffle=")
	builder.WriteString(_m.Shuffle)
	builder.WriteString(", ")
	builder.WriteString("launched_at=")
	builder.WriteString(_m.LaunchedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ActiveQuizs is a parsable slice of ActiveQuiz.
type ActiveQuizs []*ActiveQuiz
