// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/activequiz"
	"Eve/internal/database/ent/predicate"
	"Eve/internal/database/ent/quizquestion"
	"Eve/internal/database/ent/quizuseranswer"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ActiveQuizUpdate is the builder for updating ActiveQuiz entities.
type ActiveQuizUpdate struct {
	config
	hooks    []Hook
	mutation *ActiveQuizMutation
}

// Where appends a list predicates to the ActiveQuizUpdate builder.
func (_u *ActiveQuizUpdate) Where(ps ...predicate.ActiveQuiz) *ActiveQuizUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuestionID sets the "question_id" field.
func (_u *ActiveQuizUpdate) SetQuestionID(v string) *ActiveQuizUpdate {
	_u.mutation.SetQuestionID(v)
	return _u
}

// SetNillableQuestionID sets the "question_id" field if the given value is not nil.
func (_u *ActiveQuizUpdate) SetNillableQuestionID(v *string) *ActiveQuizUpdate {
	if v != nil {
		_u.SetQuestionID(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *ActiveQuizUpdate) SetMessageID(v string) *ActiveQuizUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *ActiveQuizUpdate) SetNillableMessageID(v *string) *ActiveQuizUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ActiveQuizUpdate) SetChannelID(v string) *ActiveQuizUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ActiveQuizUpdate) SetNillableChannelID(v *string) *ActiveQuizUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *ActiveQuizUpdate) SetGuildID(v string) *ActiveQuizUpdate {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *ActiveQuizUpdate) SetNillableGuildID(v *string) *ActiveQuizUpdate {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetShuffle sets the "shuffle" field.
func (_u *ActiveQuizUpdate) SetShuffle(v string) *ActiveQuizUpdate {
	_u.mutation.SetShuffle(v)
	return _u
}

// SetNillableShuffle sets the "shuffle" field if the given value is not nil.
func (_u *ActiveQuizUpdate) SetNillableShuffle(v *string) *ActiveQuizUpdate {
	if v != nil {
		_u.SetShuffle(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ActiveQuizUpdate) SetExpiresAt(v time.Time) *ActiveQuizUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ActiveQuizUpdate) SetNillableExpiresAt(v *time.Time) *ActiveQuizUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetQuestion sets the "question" edge to the QuizQuestion entity.
func (_u *ActiveQuizUpdate) SetQuestion(v *QuizQuestion) *ActiveQuizUpdate {
	return _u.SetQuestionID(v.ID)
}

// AddUserAnswerIDs adds the "user_answers" edge to the QuizUserAnswer entity by IDs.
func (_u *ActiveQuizUpdate) AddUserAnswerIDs(ids ...string) *ActiveQuizUpdate {
	_u.mutation.AddUserAnswerIDs(ids...)
	return _u
}

// AddUserAnswers adds the "user_answers" edges to the QuizUserAnswer entity.
func (_u *ActiveQuizUpdate) AddUserAnswers(v ...*QuizUserAnswer) *ActiveQuizUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserAnswerIDs(ids...)
}

// Mutation returns the ActiveQuizMutation object of the builder.
func (_u *ActiveQuizUpdate) Mutation() *ActiveQuizMutation {
	return _u.mutation
}

// ClearQuestion clears the "question" edge to the QuizQuestion entity.
func (_u *ActiveQuizUpdate) ClearQuestion() *ActiveQuizUpdate {
	_u.mutation.ClearQuestion()
	return _u
}

// ClearUserAnswers clears all "user_answers" edges to the QuizUserAnswer entity.
func (_u *ActiveQuizUpdate) ClearUserAnswers() *ActiveQuizUpdate {
	_u.mutation.ClearUserAnswers()
	return _u
}

// RemoveUserAnswerIDs removes the "user_answers" edge to QuizUserAnswer entities by IDs.
func (_u *ActiveQuizUpdate) RemoveUserAnswerIDs(ids ...string) *ActiveQuizUpdate {
	_u.mutation.RemoveUserAnswerIDs(ids...)
	return _u
}

// RemoveUserAnswers removes "user_answers" edges to QuizUserAnswer entities.
func (_u *ActiveQuizUpdate) RemoveUserAnswers(v ...*QuizUserAnswer) *ActiveQuizUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserAnswerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActiveQuizUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActiveQuizUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActiveQuizUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActiveQuizUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActiveQuizUpdate) check() error {
	if v, ok := _u.mutation.Shuffle(); ok {
		if err := activequiz.ShuffleValidator(v); err != nil {
			return &ValidationError{Name: "shuffle", err: fmt.Errorf(`ent: validator failed for field "ActiveQuiz.shuffle": %w`, err)}
		}
	}
	if _u.mutation.QuestionCleared() && len(_u.mutation.QuestionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActiveQuiz.question"`)
	}
	return nil
}

func (_u *ActiveQuizUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activequiz.Table, activequiz.Columns, sqlgraph.NewFieldSpec(activequiz.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(activequiz.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(activequiz.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(activequiz.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Shuffle(); ok {
		_spec.SetField(activequiz.FieldShuffle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(activequiz.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activequiz.QuestionTable,
			Columns: []string{activequiz.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizquestion.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activequiz.QuestionTable,
			Columns: []string{activequiz.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizquestion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activequiz.UserAnswersTable,
			Columns: []string{activequiz.UserAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizuseranswer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserAnswersIDs(); len(nodes) > 0 && !_u.mutation.UserAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activequiz.UserAnswersTable,
			Columns: []string{activequiz.UserAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizuseranswer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activequiz.UserAnswersTable,
			Columns: []string{activequiz.UserAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizuseranswer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activequiz.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActiveQuizUpdateOne is the builder for updating a single ActiveQuiz entity.
type ActiveQuizUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActiveQuizMutation
}

// SetQuestionID sets the "question_id" field.
func (_u *ActiveQuizUpdateOne) SetQuestionID(v string) *ActiveQuizUpdateOne {
	_u.mutation.SetQuestionID(v)
	return _u
}

// SetNillableQuestionID sets the "question_id" field if the given value is not nil.
func (_u *ActiveQuizUpdateOne) SetNillableQuestionID(v *string) *ActiveQuizUpdateOne {
	if v != nil {
		_u.SetQuestionID(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *ActiveQuizUpdateOne) SetMessageID(v string) *ActiveQuizUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *ActiveQuizUpdateOne) SetNillableMessageID(v *string) *ActiveQuizUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ActiveQuizUpdateOne) SetChannelID(v string) *ActiveQuizUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ActiveQuizUpdateOne) SetNillableChannelID(v *string) *ActiveQuizUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *ActiveQuizUpdateOne) SetGuildID(v string) *ActiveQuizUpdateOne {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *ActiveQuizUpdateOne) SetNillableGuildID(v *string) *ActiveQuizUpdateOne {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetShuffle sets the "shuffle" field.
func (_u *ActiveQuizUpdateOne) SetShuffle(v string) *ActiveQuizUpdateOne {
	_u.mutation.SetShuffle(v)
	return _u
}

// SetNillableShuffle sets the "shuffle" field if the given value is not nil.
func (_u *ActiveQuizUpdateOne) SetNillableShuffle(v *string) *ActiveQuizUpdateOne {
	if v != nil {
		_u.SetShuffle(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ActiveQuizUpdateOne) SetExpiresAt(v time.Time) *ActiveQuizUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ActiveQuizUpdateOne) SetNillableExpiresAt(v *time.Time) *ActiveQuizUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetQuestion sets the "question" edge to the QuizQuestion entity.
func (_u *ActiveQuizUpdateOne) SetQuestion(v *QuizQuestion) *ActiveQuizUpdateOne {
	return _u.SetQuestionID(v.ID)
}

// AddUserAnswerIDs adds the "user_answers" edge to the QuizUserAnswer entity by IDs.
func (_u *ActiveQuizUpdateOne) AddUserAnswerIDs(ids ...string) *ActiveQuizUpdateOne {
	_u.mutation.AddUserAnswerIDs(ids...)
	return _u
}

// AddUserAnswers adds the "user_answers" edges to the QuizUserAnswer entity.
func (_u *ActiveQuizUpdateOne) AddUserAnswers(v ...*QuizUserAnswer) *ActiveQuizUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserAnswerIDs(ids...)
}

// Mutation returns the ActiveQuizMutation object of the builder.
func (_u *ActiveQuizUpdateOne) Mutation() *ActiveQuizMutation {
	return _u.mutation
}

// ClearQuestion clears the "question" edge to the QuizQuestion entity.
func (_u *ActiveQuizUpdateOne) ClearQuestion() *ActiveQuizUpdateOne {
	_u.mutation.ClearQuestion()
	return _u
}

// ClearUserAnswers clears all "user_answers" edges to the QuizUserAnswer entity.
func (_u *ActiveQuizUpdateOne) ClearUserAnswers() *ActiveQuizUpdateOne {
	_u.mutation.ClearUserAnswers()
	return _u
}

// RemoveUserAnswerIDs removes the "user_answers" edge to QuizUserAnswer entities by IDs.
func (_u *ActiveQuizUpdateOne) RemoveUserAnswerIDs(ids ...string) *ActiveQuizUpdateOne {
	_u.mutation.RemoveUserAnswerIDs(ids...)
	return _u
}

// RemoveUserAnswers removes "user_answers" edges to QuizUserAnswer entities.
func (_u *ActiveQuizUpdateOne) RemoveUserAnswers(v ...*QuizUserAnswer) *ActiveQuizUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserAnswerIDs(ids...)
}

// Where appends a list predicates to the ActiveQuizUpdate builder.
func (_u *ActiveQuizUpdateOne) Where(ps ...predicate.ActiveQuiz) *ActiveQuizUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActiveQuizUpdateOne) Select(field string, fields ...string) *ActiveQuizUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActiveQuiz entity.
func (_u *ActiveQuizUpdateOne) Save(ctx context.Context) (*ActiveQuiz, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActiveQuizUpdateOne) SaveX(ctx context.Context) *ActiveQuiz {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActiveQuizUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActiveQuizUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActiveQuizUpdateOne) check() error {
	if v, ok := _u.mutation.Shuffle(); ok {
		if err := activequiz.ShuffleValidator(v); err != nil {
			return &ValidationError{Name: "shuffle", err: fmt.Errorf(`ent: validator failed for field "ActiveQuiz.shuffle": %w`, err)}
		}
	}
	if _u.mutation.QuestionCleared() && len(_u.mutation.QuestionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActiveQuiz.question"`)
	}
	return nil
}

func (_u *ActiveQuizUpdateOne) sqlSave(ctx context.Context) (_node *ActiveQuiz, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activequiz.Table, activequiz.Columns, sqlgraph.NewFieldSpec(activequiz.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActiveQuiz.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activequiz.FieldID)
		for _, f := range fields {
			if !activequiz.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != activequiz.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(activequiz.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(activequiz.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(activequiz.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Shuffle(); ok {
		_spec.SetField(activequiz.FieldShuffle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(activequiz.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activequiz.QuestionTable,
			Columns: []string{activequiz.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizquestion.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activequiz.QuestionTable,
			Columns: []string{activequiz.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizquestion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activequiz.UserAnswersTable,
			Columns: []string{activequiz.UserAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizuseranswer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserAnswersIDs(); len(nodes) > 0 && !_u.mutation.UserAnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activequiz.UserAnswersTable,
			Columns: []string{activequiz.UserAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizuseranswer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activequiz.UserAnswersTable,
			Columns: []string{activequiz.UserAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizuseranswer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ActiveQuiz{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activequiz.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
