// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"Eve/internal/database/ent/migrate"

	"Eve/internal/database/ent/birthday"
	"Eve/internal/database/ent/guildconfig"
	"Eve/internal/database/ent/quote"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Birthday is the client for interacting with the Birthday builders.
	Birthday *BirthdayClient
	// GuildConfig is the client for interacting with the GuildConfig builders.
	GuildConfig *GuildConfigClient
	// Quote is the client for interacting with the Quote builders.
	Quote *QuoteClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Birthday = NewBirthdayClient(c.config)
	c.GuildConfig = NewGuildConfigClient(c.config)
	c.Quote = NewQuoteClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Birthday:    NewBirthdayClient(cfg),
		GuildConfig: NewGuildConfigClient(cfg),
		Quote:       NewQuoteClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Birthday:    NewBirthdayClient(cfg),
		GuildConfig: NewGuildConfigClient(cfg),
		Quote:       NewQuoteClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Birthday.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Birthday.Use(hooks...)
	c.GuildConfig.Use(hooks...)
	c.Quote.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Birthday.Intercept(interceptors...)
	c.GuildConfig.Intercept(interceptors...)
	c.Quote.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BirthdayMutation:
		return c.Birthday.mutate(ctx, m)
	case *GuildConfigMutation:
		return c.GuildConfig.mutate(ctx, m)
	case *QuoteMutation:
		return c.Quote.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BirthdayClient is a client for the Birthday schema.
type BirthdayClient struct {
	config
}

// NewBirthdayClient returns a client for the Birthday from the given config.
func NewBirthdayClient(c config) *BirthdayClient {
	return &BirthdayClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `birthday.Hooks(f(g(h())))`.
func (c *BirthdayClient) Use(hooks ...Hook) {
	c.hooks.Birthday = append(c.hooks.Birthday, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `birthday.Intercept(f(g(h())))`.
func (c *BirthdayClient) Intercept(interceptors ...Interceptor) {
	c.inters.Birthday = append(c.inters.Birthday, interceptors...)
}

// Create returns a builder for creating a Birthday entity.
func (c *BirthdayClient) Create() *BirthdayCreate {
	mutation := newBirthdayMutation(c.config, OpCreate)
	return &BirthdayCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Birthday entities.
func (c *BirthdayClient) CreateBulk(builders ...*BirthdayCreate) *BirthdayCreateBulk {
	return &BirthdayCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BirthdayClient) MapCreateBulk(slice any, setFunc func(*BirthdayCreate, int)) *BirthdayCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BirthdayCreateBulk{err: fmt.Errorf("calling to BirthdayClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BirthdayCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BirthdayCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Birthday.
func (c *BirthdayClient) Update() *BirthdayUpdate {
	mutation := newBirthdayMutation(c.config, OpUpdate)
	return &BirthdayUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BirthdayClient) UpdateOne(_m *Birthday) *BirthdayUpdateOne {
	mutation := newBirthdayMutation(c.config, OpUpdateOne, withBirthday(_m))
	return &BirthdayUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BirthdayClient) UpdateOneID(id int) *BirthdayUpdateOne {
	mutation := newBirthdayMutation(c.config, OpUpdateOne, withBirthdayID(id))
	return &BirthdayUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Birthday.
func (c *BirthdayClient) Delete() *BirthdayDelete {
	mutation := newBirthdayMutation(c.config, OpDelete)
	return &BirthdayDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BirthdayClient) DeleteOne(_m *Birthday) *BirthdayDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BirthdayClient) DeleteOneID(id int) *BirthdayDeleteOne {
	builder := c.Delete().Where(birthday.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BirthdayDeleteOne{builder}
}

// Query returns a query builder for Birthday.
func (c *BirthdayClient) Query() *BirthdayQuery {
	return &BirthdayQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBirthday},
		inters: c.Interceptors(),
	}
}

// Get returns a Birthday entity by its id.
func (c *BirthdayClient) Get(ctx context.Context, id int) (*Birthday, error) {
	return c.Query().Where(birthday.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BirthdayClient) GetX(ctx context.Context, id int) *Birthday {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BirthdayClient) Hooks() []Hook {
	return c.hooks.Birthday
}

// Interceptors returns the client interceptors.
func (c *BirthdayClient) Interceptors() []Interceptor {
	return c.inters.Birthday
}

func (c *BirthdayClient) mutate(ctx context.Context, m *BirthdayMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BirthdayCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BirthdayUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BirthdayUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BirthdayDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Birthday mutation op: %q", m.Op())
	}
}

// GuildConfigClient is a client for the GuildConfig schema.
type GuildConfigClient struct {
	config
}

// NewGuildConfigClient returns a client for the GuildConfig from the given config.
func NewGuildConfigClient(c config) *GuildConfigClient {
	return &GuildConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `guildconfig.Hooks(f(g(h())))`.
func (c *GuildConfigClient) Use(hooks ...Hook) {
	c.hooks.GuildConfig = append(c.hooks.GuildConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `guildconfig.Intercept(f(g(h())))`.
func (c *GuildConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.GuildConfig = append(c.inters.GuildConfig, interceptors...)
}

// Create returns a builder for creating a GuildConfig entity.
func (c *GuildConfigClient) Create() *GuildConfigCreate {
	mutation := newGuildConfigMutation(c.config, OpCreate)
	return &GuildConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GuildConfig entities.
func (c *GuildConfigClient) CreateBulk(builders ...*GuildConfigCreate) *GuildConfigCreateBulk {
	return &GuildConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GuildConfigClient) MapCreateBulk(slice any, setFunc func(*GuildConfigCreate, int)) *GuildConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GuildConfigCreateBulk{err: fmt.Errorf("calling to GuildConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GuildConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GuildConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GuildConfig.
func (c *GuildConfigClient) Update() *GuildConfigUpdate {
	mutation := newGuildConfigMutation(c.config, OpUpdate)
	return &GuildConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GuildConfigClient) UpdateOne(_m *GuildConfig) *GuildConfigUpdateOne {
	mutation := newGuildConfigMutation(c.config, OpUpdateOne, withGuildConfig(_m))
	return &GuildConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GuildConfigClient) UpdateOneID(id int) *GuildConfigUpdateOne {
	mutation := newGuildConfigMutation(c.config, OpUpdateOne, withGuildConfigID(id))
	return &GuildConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GuildConfig.
func (c *GuildConfigClient) Delete() *GuildConfigDelete {
	mutation := newGuildConfigMutation(c.config, OpDelete)
	return &GuildConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GuildConfigClient) DeleteOne(_m *GuildConfig) *GuildConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GuildConfigClient) DeleteOneID(id int) *GuildConfigDeleteOne {
	builder := c.Delete().Where(guildconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GuildConfigDeleteOne{builder}
}

// Query returns a query builder for GuildConfig.
func (c *GuildConfigClient) Query() *GuildConfigQuery {
	return &GuildConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGuildConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a GuildConfig entity by its id.
func (c *GuildConfigClient) Get(ctx context.Context, id int) (*GuildConfig, error) {
	return c.Query().Where(guildconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GuildConfigClient) GetX(ctx context.Context, id int) *GuildConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GuildConfigClient) Hooks() []Hook {
	return c.hooks.GuildConfig
}

// Interceptors returns the client interceptors.
func (c *GuildConfigClient) Interceptors() []Interceptor {
	return c.inters.GuildConfig
}

func (c *GuildConfigClient) mutate(ctx context.Context, m *GuildConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GuildConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GuildConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GuildConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GuildConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GuildConfig mutation op: %q", m.Op())
	}
}

// QuoteClient is a client for the Quote schema.
type QuoteClient struct {
	config
}

// NewQuoteClient returns a client for the Quote from the given config.
func NewQuoteClient(c config) *QuoteClient {
	return &QuoteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `quote.Hooks(f(g(h())))`.
func (c *QuoteClient) Use(hooks ...Hook) {
	c.hooks.Quote = append(c.hooks.Quote, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `quote.Intercept(f(g(h())))`.
func (c *QuoteClient) Intercept(interceptors ...Interceptor) {
	c.inters.Quote = append(c.inters.Quote, interceptors...)
}

// Create returns a builder for creating a Quote entity.
func (c *QuoteClient) Create() *QuoteCreate {
	mutation := newQuoteMutation(c.config, OpCreate)
	return &QuoteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Quote entities.
func (c *QuoteClient) CreateBulk(builders ...*QuoteCreate) *QuoteCreateBulk {
	return &QuoteCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *QuoteClient) MapCreateBulk(slice any, setFunc func(*QuoteCreate, int)) *QuoteCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &QuoteCreateBulk{err: fmt.Errorf("calling to QuoteClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*QuoteCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &QuoteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Quote.
func (c *QuoteClient) Update() *QuoteUpdate {
	mutation := newQuoteMutation(c.config, OpUpdate)
	return &QuoteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *QuoteClient) UpdateOne(_m *Quote) *QuoteUpdateOne {
	mutation := newQuoteMutation(c.config, OpUpdateOne, withQuote(_m))
	return &QuoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *QuoteClient) UpdateOneID(id string) *QuoteUpdateOne {
	mutation := newQuoteMutation(c.config, OpUpdateOne, withQuoteID(id))
	return &QuoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Quote.
func (c *QuoteClient) Delete() *QuoteDelete {
	mutation := newQuoteMutation(c.config, OpDelete)
	return &QuoteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *QuoteClient) DeleteOne(_m *Quote) *QuoteDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *QuoteClient) DeleteOneID(id string) *QuoteDeleteOne {
	builder := c.Delete().Where(quote.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &QuoteDeleteOne{builder}
}

// Query returns a query builder for Quote.
func (c *QuoteClient) Query() *QuoteQuery {
	return &QuoteQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeQuote},
		inters: c.Interceptors(),
	}
}

// Get returns a Quote entity by its id.
func (c *QuoteClient) Get(ctx context.Context, id string) (*Quote, error) {
	return c.Query().Where(quote.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *QuoteClient) GetX(ctx context.Context, id string) *Quote {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *QuoteClient) Hooks() []Hook {
	return c.hooks.Quote
}

// Interceptors returns the client interceptors.
func (c *QuoteClient) Interceptors() []Interceptor {
	return c.inters.Quote
}

func (c *QuoteClient) mutate(ctx context.Context, m *QuoteMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&QuoteCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&QuoteUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&QuoteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&QuoteDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Quote mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Birthday, GuildConfig, Quote []ent.Hook
	}
	inters struct {
		Birthday, GuildConfig, Quote []ent.Interceptor
	}
)
