// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/guildconfig"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GuildConfigCreate is the builder for creating a GuildConfig entity.
type GuildConfigCreate struct {
	config
	mutation *GuildConfigMutation
	hooks    []Hook
}

// SetGuildID sets the "guild_id" field.
func (_c *GuildConfigCreate) SetGuildID(v string) *GuildConfigCreate {
	_c.mutation.SetGuildID(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *GuildConfigCreate) SetKey(v string) *GuildConfigCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *GuildConfigCreate) SetValue(v string) *GuildConfigCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GuildConfigCreate) SetCreatedAt(v time.Time) *GuildConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GuildConfigCreate) SetNillableCreatedAt(v *time.Time) *GuildConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GuildConfigCreate) SetUpdatedAt(v time.Time) *GuildConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GuildConfigCreate) SetNillableUpdatedAt(v *time.Time) *GuildConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the GuildConfigMutation object of the builder.
func (_c *GuildConfigCreate) Mutation() *GuildConfigMutation {
	return _c.mutation
}

// Save creates the GuildConfig in the database.
func (_c *GuildConfigCreate) Save(ctx context.Context) (*GuildConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GuildConfigCreate) SaveX(ctx context.Context) *GuildConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GuildConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GuildConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GuildConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := guildconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := guildconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GuildConfigCreate) check() error {
	if _, ok := _c.mutation.GuildID(); !ok {
		return &ValidationError{Name: "guild_id", err: errors.New(`ent: missing required field "GuildConfig.guild_id"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "GuildConfig.key"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "GuildConfig.value"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GuildConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GuildConfig.updated_at"`)}
	}
	return nil
}

func (_c *GuildConfigCreate) sqlSave(ctx context.Context) (*GuildConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GuildConfigCreate) createSpec() (*GuildConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &GuildConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(guildconfig.Table, sqlgraph.NewFieldSpec(guildconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GuildID(); ok {
		_spec.SetField(guildconfig.FieldGuildID, field.TypeString, value)
		_node.GuildID = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(guildconfig.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(guildconfig.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(guildconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(guildconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GuildConfigCreateBulk is the builder for creating many GuildConfig entities in bulk.
type GuildConfigCreateBulk struct {
	config
	err      error
	builders []*GuildConfigCreate
}

// Save creates the GuildConfig entities in the database.
func (_c *GuildConfigCreateBulk) Save(ctx context.Context) ([]*GuildConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GuildConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GuildConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GuildConfigCreateBulk) SaveX(ctx context.Context) []*GuildConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GuildConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GuildConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
