// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/lotogame"
	"Eve/internal/database/ent/lotoplayer"
	"Eve/internal/database/ent/lototicket"
	"Eve/internal/database/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LotoTicketUpdate is the builder for updating LotoTicket entities.
type LotoTicketUpdate struct {
	config
	hooks    []Hook
	mutation *LotoTicketMutation
}

// Where appends a list predicates to the LotoTicketUpdate builder.
func (_u *LotoTicketUpdate) Where(ps ...predicate.LotoTicket) *LotoTicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *LotoTicketUpdate) SetGameID(v string) *LotoTicketUpdate {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *LotoTicketUpdate) SetNillableGameID(v *string) *LotoTicketUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetPlayerID sets the "player_id" field.
func (_u *LotoTicketUpdate) SetPlayerID(v string) *LotoTicketUpdate {
	_u.mutation.SetPlayerID(v)
	return _u
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (_u *LotoTicketUpdate) SetNillablePlayerID(v *string) *LotoTicketUpdate {
	if v != nil {
		_u.SetPlayerID(*v)
	}
	return _u
}

// SetSellerID sets the "seller_id" field.
func (_u *LotoTicketUpdate) SetSellerID(v string) *LotoTicketUpdate {
	_u.mutation.SetSellerID(v)
	return _u
}

// SetNillableSellerID sets the "seller_id" field if the given value is not nil.
func (_u *LotoTicketUpdate) SetNillableSellerID(v *string) *LotoTicketUpdate {
	if v != nil {
		_u.SetSellerID(*v)
	}
	return _u
}

// SetNumber sets the "number" field.
func (_u *LotoTicketUpdate) SetNumber(v int) *LotoTicketUpdate {
	_u.mutation.ResetNumber()
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *LotoTicketUpdate) SetNillableNumber(v *int) *LotoTicketUpdate {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// AddNumber adds value to the "number" field.
func (_u *LotoTicketUpdate) AddNumber(v int) *LotoTicketUpdate {
	_u.mutation.AddNumber(v)
	return _u
}

// SetGame sets the "game" edge to the LotoGame entity.
func (_u *LotoTicketUpdate) SetGame(v *LotoGame) *LotoTicketUpdate {
	return _u.SetGameID(v.ID)
}

// SetPlayer sets the "player" edge to the LotoPlayer entity.
func (_u *LotoTicketUpdate) SetPlayer(v *LotoPlayer) *LotoTicketUpdate {
	return _u.SetPlayerID(v.ID)
}

// Mutation returns the LotoTicketMutation object of the builder.
func (_u *LotoTicketUpdate) Mutation() *LotoTicketMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the LotoGame entity.
func (_u *LotoTicketUpdate) ClearGame() *LotoTicketUpdate {
	_u.mutation.ClearGame()
	return _u
}

// ClearPlayer clears the "player" edge to the LotoPlayer entity.
func (_u *LotoTicketUpdate) ClearPlayer() *LotoTicketUpdate {
	_u.mutation.ClearPlayer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotoTicketUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotoTicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotoTicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotoTicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotoTicketUpdate) check() error {
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotoTicket.game"`)
	}
	if _u.mutation.PlayerCleared() && len(_u.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotoTicket.player"`)
	}
	return nil
}

func (_u *LotoTicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lototicket.Table, lototicket.Columns, sqlgraph.NewFieldSpec(lototicket.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SellerID(); ok {
		_spec.SetField(lototicket.FieldSellerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(lototicket.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumber(); ok {
		_spec.AddField(lototicket.FieldNumber, field.TypeInt, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lototicket.GameTable,
			Columns: []string{lototicket.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotogame.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lototicket.GameTable,
			Columns: []string{lototicket.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotogame.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lototicket.PlayerTable,
			Columns: []string{lototicket.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lototicket.PlayerTable,
			Columns: []string{lototicket.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lototicket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotoTicketUpdateOne is the builder for updating a single LotoTicket entity.
type LotoTicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotoTicketMutation
}

// SetGameID sets the "game_id" field.
func (_u *LotoTicketUpdateOne) SetGameID(v string) *LotoTicketUpdateOne {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *LotoTicketUpdateOne) SetNillableGameID(v *string) *LotoTicketUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetPlayerID sets the "player_id" field.
func (_u *LotoTicketUpdateOne) SetPlayerID(v string) *LotoTicketUpdateOne {
	_u.mutation.SetPlayerID(v)
	return _u
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (_u *LotoTicketUpdateOne) SetNillablePlayerID(v *string) *LotoTicketUpdateOne {
	if v != nil {
		_u.SetPlayerID(*v)
	}
	return _u
}

// SetSellerID sets the "seller_id" field.
func (_u *LotoTicketUpdateOne) SetSellerID(v string) *LotoTicketUpdateOne {
	_u.mutation.SetSellerID(v)
	return _u
}

// SetNillableSellerID sets the "seller_id" field if the given value is not nil.
func (_u *LotoTicketUpdateOne) SetNillableSellerID(v *string) *LotoTicketUpdateOne {
	if v != nil {
		_u.SetSellerID(*v)
	}
	return _u
}

// SetNumber sets the "number" field.
func (_u *LotoTicketUpdateOne) SetNumber(v int) *LotoTicketUpdateOne {
	_u.mutation.ResetNumber()
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *LotoTicketUpdateOne) SetNillableNumber(v *int) *LotoTicketUpdateOne {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// AddNumber adds value to the "number" field.
func (_u *LotoTicketUpdateOne) AddNumber(v int) *LotoTicketUpdateOne {
	_u.mutation.AddNumber(v)
	return _u
}

// SetGame sets the "game" edge to the LotoGame entity.
func (_u *LotoTicketUpdateOne) SetGame(v *LotoGame) *LotoTicketUpdateOne {
	return _u.SetGameID(v.ID)
}

// SetPlayer sets the "player" edge to the LotoPlayer entity.
func (_u *LotoTicketUpdateOne) SetPlayer(v *LotoPlayer) *LotoTicketUpdateOne {
	return _u.SetPlayerID(v.ID)
}

// Mutation returns the LotoTicketMutation object of the builder.
func (_u *LotoTicketUpdateOne) Mutation() *LotoTicketMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the LotoGame entity.
func (_u *LotoTicketUpdateOne) ClearGame() *LotoTicketUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// ClearPlayer clears the "player" edge to the LotoPlayer entity.
func (_u *LotoTicketUpdateOne) ClearPlayer() *LotoTicketUpdateOne {
	_u.mutation.ClearPlayer()
	return _u
}

// Where appends a list predicates to the LotoTicketUpdate builder.
func (_u *LotoTicketUpdateOne) Where(ps ...predicate.LotoTicket) *LotoTicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotoTicketUpdateOne) Select(field string, fields ...string) *LotoTicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotoTicket entity.
func (_u *LotoTicketUpdateOne) Save(ctx context.Context) (*LotoTicket, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotoTicketUpdateOne) SaveX(ctx context.Context) *LotoTicket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotoTicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotoTicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotoTicketUpdateOne) check() error {
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotoTicket.game"`)
	}
	if _u.mutation.PlayerCleared() && len(_u.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotoTicket.player"`)
	}
	return nil
}

func (_u *LotoTicketUpdateOne) sqlSave(ctx context.Context) (_node *LotoTicket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lototicket.Table, lototicket.Columns, sqlgraph.NewFieldSpec(lototicket.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotoTicket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lototicket.FieldID)
		for _, f := range fields {
			if !lototicket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lototicket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SellerID(); ok {
		_spec.SetField(lototicket.FieldSellerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(lototicket.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumber(); ok {
		_spec.AddField(lototicket.FieldNumber, field.TypeInt, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lototicket.GameTable,
			Columns: []string{lototicket.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotogame.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lototicket.GameTable,
			Columns: []string{lototicket.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotogame.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lototicket.PlayerTable,
			Columns: []string{lototicket.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lototicket.PlayerTable,
			Columns: []string{lototicket.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LotoTicket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lototicket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
