// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/lotogame"
	"Eve/internal/database/ent/lotoplayer"
	"Eve/internal/database/ent/lotoprize"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LotoPrizeCreate is the builder for creating a LotoPrize entity.
type LotoPrizeCreate struct {
	config
	mutation *LotoPrizeMutation
	hooks    []Hook
}

// SetGameID sets the "game_id" field.
func (_c *LotoPrizeCreate) SetGameID(v string) *LotoPrizeCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *LotoPrizeCreate) SetLabel(v string) *LotoPrizeCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *LotoPrizeCreate) SetPosition(v int) *LotoPrizeCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetWinnerPlayerID sets the "winner_player_id" field.
func (_c *LotoPrizeCreate) SetWinnerPlayerID(v string) *LotoPrizeCreate {
	_c.mutation.SetWinnerPlayerID(v)
	return _c
}

// SetNillableWinnerPlayerID sets the "winner_player_id" field if the given value is not nil.
func (_c *LotoPrizeCreate) SetNillableWinnerPlayerID(v *string) *LotoPrizeCreate {
	if v != nil {
		_c.SetWinnerPlayerID(*v)
	}
	return _c
}

// SetWinningTicketNumber sets the "winning_ticket_number" field.
func (_c *LotoPrizeCreate) SetWinningTicketNumber(v int) *LotoPrizeCreate {
	_c.mutation.SetWinningTicketNumber(v)
	return _c
}

// SetNillableWinningTicketNumber sets the "winning_ticket_number" field if the given value is not nil.
func (_c *LotoPrizeCreate) SetNillableWinningTicketNumber(v *int) *LotoPrizeCreate {
	if v != nil {
		_c.SetWinningTicketNumber(*v)
	}
	return _c
}

// SetDrawnAt sets the "drawn_at" field.
func (_c *LotoPrizeCreate) SetDrawnAt(v time.Time) *LotoPrizeCreate {
	_c.mutation.SetDrawnAt(v)
	return _c
}

// SetNillableDrawnAt sets the "drawn_at" field if the given value is not nil.
func (_c *LotoPrizeCreate) SetNillableDrawnAt(v *time.Time) *LotoPrizeCreate {
	if v != nil {
		_c.SetDrawnAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotoPrizeCreate) SetCreatedAt(v time.Time) *LotoPrizeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotoPrizeCreate) SetNillableCreatedAt(v *time.Time) *LotoPrizeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotoPrizeCreate) SetUpdatedAt(v time.Time) *LotoPrizeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotoPrizeCreate) SetNillableUpdatedAt(v *time.Time) *LotoPrizeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LotoPrizeCreate) SetID(v string) *LotoPrizeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetGame sets the "game" edge to the LotoGame entity.
func (_c *LotoPrizeCreate) SetGame(v *LotoGame) *LotoPrizeCreate {
	return _c.SetGameID(v.ID)
}

// SetWinnerID sets the "winner" edge to the LotoPlayer entity by ID.
func (_c *LotoPrizeCreate) SetWinnerID(id string) *LotoPrizeCreate {
	_c.mutation.SetWinnerID(id)
	return _c
}

// SetNillableWinnerID sets the "winner" edge to the LotoPlayer entity by ID if the given value is not nil.
func (_c *LotoPrizeCreate) SetNillableWinnerID(id *string) *LotoPrizeCreate {
	if id != nil {
		_c = _c.SetWinnerID(*id)
	}
	return _c
}

// SetWinner sets the "winner" edge to the LotoPlayer entity.
func (_c *LotoPrizeCreate) SetWinner(v *LotoPlayer) *LotoPrizeCreate {
	return _c.SetWinnerID(v.ID)
}

// Mutation returns the LotoPrizeMutation object of the builder.
func (_c *LotoPrizeCreate) Mutation() *LotoPrizeMutation {
	return _c.mutation
}

// Save creates the LotoPrize in the database.
func (_c *LotoPrizeCreate) Save(ctx context.Context) (*LotoPrize, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotoPrizeCreate) SaveX(ctx context.Context) *LotoPrize {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotoPrizeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotoPrizeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotoPrizeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotoprize.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotoprize.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotoPrizeCreate) check() error {
	if _, ok := _c.mutation.GameID(); !ok {
		return &ValidationError{Name: "game_id", err: errors.New(`ent: missing required field "LotoPrize.game_id"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "LotoPrize.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := lotoprize.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "LotoPrize.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "LotoPrize.position"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotoPrize.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotoPrize.updated_at"`)}
	}
	if len(_c.mutation.GameIDs()) == 0 {
		return &ValidationError{Name: "game", err: errors.New(`ent: missing required edge "LotoPrize.game"`)}
	}
	return nil
}

func (_c *LotoPrizeCreate) sqlSave(ctx context.Context) (*LotoPrize, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected LotoPrize.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotoPrizeCreate) createSpec() (*LotoPrize, *sqlgraph.CreateSpec) {
	var (
		_node = &LotoPrize{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotoprize.Table, sqlgraph.NewFieldSpec(lotoprize.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(lotoprize.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(lotoprize.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.WinningTicketNumber(); ok {
		_spec.SetField(lotoprize.FieldWinningTicketNumber, field.TypeInt, value)
		_node.WinningTicketNumber = value
	}
	if value, ok := _c.mutation.DrawnAt(); ok {
		_spec.SetField(lotoprize.FieldDrawnAt, field.TypeTime, value)
		_node.DrawnAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotoprize.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotoprize.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotoprize.GameTable,
			Columns: []string{lotoprize.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotogame.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GameID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WinnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotoprize.WinnerTable,
			Columns: []string{lotoprize.WinnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WinnerPlayerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LotoPrizeCreateBulk is the builder for creating many LotoPrize entities in bulk.
type LotoPrizeCreateBulk struct {
	config
	err      error
	builders []*LotoPrizeCreate
}

// Save creates the LotoPrize entities in the database.
func (_c *LotoPrizeCreateBulk) Save(ctx context.Context) ([]*LotoPrize, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotoPrize, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotoPrizeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotoPrizeCreateBulk) SaveX(ctx context.Context) []*LotoPrize {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotoPrizeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotoPrizeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
