// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/lotogame"
	"Eve/internal/database/ent/lotoplayer"
	"Eve/internal/database/ent/lotoprize"
	"Eve/internal/database/ent/lototicket"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LotoPlayerCreate is the builder for creating a LotoPlayer entity.
type LotoPlayerCreate struct {
	config
	mutation *LotoPlayerMutation
	hooks    []Hook
}

// SetGameID sets the "game_id" field.
func (_c *LotoPlayerCreate) SetGameID(v string) *LotoPlayerCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *LotoPlayerCreate) SetName(v string) *LotoPlayerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLastPlay sets the "last_play" field.
func (_c *LotoPlayerCreate) SetLastPlay(v time.Time) *LotoPlayerCreate {
	_c.mutation.SetLastPlay(v)
	return _c
}

// SetNillableLastPlay sets the "last_play" field if the given value is not nil.
func (_c *LotoPlayerCreate) SetNillableLastPlay(v *time.Time) *LotoPlayerCreate {
	if v != nil {
		_c.SetLastPlay(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotoPlayerCreate) SetCreatedAt(v time.Time) *LotoPlayerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotoPlayerCreate) SetNillableCreatedAt(v *time.Time) *LotoPlayerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotoPlayerCreate) SetUpdatedAt(v time.Time) *LotoPlayerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotoPlayerCreate) SetNillableUpdatedAt(v *time.Time) *LotoPlayerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LotoPlayerCreate) SetID(v string) *LotoPlayerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetGame sets the "game" edge to the LotoGame entity.
func (_c *LotoPlayerCreate) SetGame(v *LotoGame) *LotoPlayerCreate {
	return _c.SetGameID(v.ID)
}

// AddTicketIDs adds the "tickets" edge to the LotoTicket entity by IDs.
func (_c *LotoPlayerCreate) AddTicketIDs(ids ...string) *LotoPlayerCreate {
	_c.mutation.AddTicketIDs(ids...)
	return _c
}

// AddTickets adds the "tickets" edges to the LotoTicket entity.
func (_c *LotoPlayerCreate) AddTickets(v ...*LotoTicket) *LotoPlayerCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketIDs(ids...)
}

// AddWonPrizeIDs adds the "won_prizes" edge to the LotoPrize entity by IDs.
func (_c *LotoPlayerCreate) AddWonPrizeIDs(ids ...string) *LotoPlayerCreate {
	_c.mutation.AddWonPrizeIDs(ids...)
	return _c
}

// AddWonPrizes adds the "won_prizes" edges to the LotoPrize entity.
func (_c *LotoPlayerCreate) AddWonPrizes(v ...*LotoPrize) *LotoPlayerCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWonPrizeIDs(ids...)
}

// Mutation returns the LotoPlayerMutation object of the builder.
func (_c *LotoPlayerCreate) Mutation() *LotoPlayerMutation {
	return _c.mutation
}

// Save creates the LotoPlayer in the database.
func (_c *LotoPlayerCreate) Save(ctx context.Context) (*LotoPlayer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotoPlayerCreate) SaveX(ctx context.Context) *LotoPlayer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotoPlayerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotoPlayerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotoPlayerCreate) defaults() {
	if _, ok := _c.mutation.LastPlay(); !ok {
		v := lotoplayer.DefaultLastPlay()
		_c.mutation.SetLastPlay(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotoplayer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotoplayer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotoPlayerCreate) check() error {
	if _, ok := _c.mutation.GameID(); !ok {
		return &ValidationError{Name: "game_id", err: errors.New(`ent: missing required field "LotoPlayer.game_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "LotoPlayer.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := lotoplayer.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotoPlayer.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastPlay(); !ok {
		return &ValidationError{Name: "last_play", err: errors.New(`ent: missing required field "LotoPlayer.last_play"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotoPlayer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotoPlayer.updated_at"`)}
	}
	if len(_c.mutation.GameIDs()) == 0 {
		return &ValidationError{Name: "game", err: errors.New(`ent: missing required edge "LotoPlayer.game"`)}
	}
	return nil
}

func (_c *LotoPlayerCreate) sqlSave(ctx context.Context) (*LotoPlayer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected LotoPlayer.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotoPlayerCreate) createSpec() (*LotoPlayer, *sqlgraph.CreateSpec) {
	var (
		_node = &LotoPlayer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotoplayer.Table, sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(lotoplayer.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.LastPlay(); ok {
		_spec.SetField(lotoplayer.FieldLastPlay, field.TypeTime, value)
		_node.LastPlay = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotoplayer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotoplayer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotoplayer.GameTable,
			Columns: []string{lotoplayer.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotogame.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GameID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotoplayer.TicketsTable,
			Columns: []string{lotoplayer.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lototicket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WonPrizesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotoplayer.WonPrizesTable,
			Columns: []string{lotoplayer.WonPrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoprize.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LotoPlayerCreateBulk is the builder for creating many LotoPlayer entities in bulk.
type LotoPlayerCreateBulk struct {
	config
	err      error
	builders []*LotoPlayerCreate
}

// Save creates the LotoPlayer entities in the database.
func (_c *LotoPlayerCreateBulk) Save(ctx context.Context) ([]*LotoPlayer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotoPlayer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotoPlayerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotoPlayerCreateBulk) SaveX(ctx context.Context) []*LotoPlayer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotoPlayerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotoPlayerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
