// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/lotogame"
	"Eve/internal/database/ent/lotoplayer"
	"Eve/internal/database/ent/lotoprize"
	"Eve/internal/database/ent/lototicket"
	"Eve/internal/database/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LotoGameUpdate is the builder for updating LotoGame entities.
type LotoGameUpdate struct {
	config
	hooks    []Hook
	mutation *LotoGameMutation
}

// Where appends a list predicates to the LotoGameUpdate builder.
func (_u *LotoGameUpdate) Where(ps ...predicate.LotoGame) *LotoGameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *LotoGameUpdate) SetGuildID(v string) *LotoGameUpdate {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *LotoGameUpdate) SetNillableGuildID(v *string) *LotoGameUpdate {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LotoGameUpdate) SetName(v string) *LotoGameUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LotoGameUpdate) SetNillableName(v *string) *LotoGameUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *LotoGameUpdate) SetActive(v bool) *LotoGameUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *LotoGameUpdate) SetNillableActive(v *bool) *LotoGameUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetTicketPrice sets the "ticket_price" field.
func (_u *LotoGameUpdate) SetTicketPrice(v int) *LotoGameUpdate {
	_u.mutation.ResetTicketPrice()
	_u.mutation.SetTicketPrice(v)
	return _u
}

// SetNillableTicketPrice sets the "ticket_price" field if the given value is not nil.
func (_u *LotoGameUpdate) SetNillableTicketPrice(v *int) *LotoGameUpdate {
	if v != nil {
		_u.SetTicketPrice(*v)
	}
	return _u
}

// AddTicketPrice adds value to the "ticket_price" field.
func (_u *LotoGameUpdate) AddTicketPrice(v int) *LotoGameUpdate {
	_u.mutation.AddTicketPrice(v)
	return _u
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (_u *LotoGameUpdate) SetCooldownMinutes(v int) *LotoGameUpdate {
	_u.mutation.ResetCooldownMinutes()
	_u.mutation.SetCooldownMinutes(v)
	return _u
}

// SetNillableCooldownMinutes sets the "cooldown_minutes" field if the given value is not nil.
func (_u *LotoGameUpdate) SetNillableCooldownMinutes(v *int) *LotoGameUpdate {
	if v != nil {
		_u.SetCooldownMinutes(*v)
	}
	return _u
}

// AddCooldownMinutes adds value to the "cooldown_minutes" field.
func (_u *LotoGameUpdate) AddCooldownMinutes(v int) *LotoGameUpdate {
	_u.mutation.AddCooldownMinutes(v)
	return _u
}

// SetMaxTicketsPerPurchase sets the "max_tickets_per_purchase" field.
func (_u *LotoGameUpdate) SetMaxTicketsPerPurchase(v int) *LotoGameUpdate {
	_u.mutation.ResetMaxTicketsPerPurchase()
	_u.mutation.SetMaxTicketsPerPurchase(v)
	return _u
}

// SetNillableMaxTicketsPerPurchase sets the "max_tickets_per_purchase" field if the given value is not nil.
func (_u *LotoGameUpdate) SetNillableMaxTicketsPerPurchase(v *int) *LotoGameUpdate {
	if v != nil {
		_u.SetMaxTicketsPerPurchase(*v)
	}
	return _u
}

// AddMaxTicketsPerPurchase adds value to the "max_tickets_per_purchase" field.
func (_u *LotoGameUpdate) AddMaxTicketsPerPurchase(v int) *LotoGameUpdate {
	_u.mutation.AddMaxTicketsPerPurchase(v)
	return _u
}

// ClearMaxTicketsPerPurchase clears the value of the "max_tickets_per_purchase" field.
func (_u *LotoGameUpdate) ClearMaxTicketsPerPurchase() *LotoGameUpdate {
	_u.mutation.ClearMaxTicketsPerPurchase()
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *LotoGameUpdate) SetMessageID(v string) *LotoGameUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *LotoGameUpdate) SetNillableMessageID(v *string) *LotoGameUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// ClearMessageID clears the value of the "message_id" field.
func (_u *LotoGameUpdate) ClearMessageID() *LotoGameUpdate {
	_u.mutation.ClearMessageID()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *LotoGameUpdate) SetChannelID(v string) *LotoGameUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *LotoGameUpdate) SetNillableChannelID(v *string) *LotoGameUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *LotoGameUpdate) ClearChannelID() *LotoGameUpdate {
	_u.mutation.ClearChannelID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotoGameUpdate) SetUpdatedAt(v time.Time) *LotoGameUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPlayerIDs adds the "players" edge to the LotoPlayer entity by IDs.
func (_u *LotoGameUpdate) AddPlayerIDs(ids ...string) *LotoGameUpdate {
	_u.mutation.AddPlayerIDs(ids...)
	return _u
}

// AddPlayers adds the "players" edges to the LotoPlayer entity.
func (_u *LotoGameUpdate) AddPlayers(v ...*LotoPlayer) *LotoGameUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlayerIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the LotoTicket entity by IDs.
func (_u *LotoGameUpdate) AddTicketIDs(ids ...string) *LotoGameUpdate {
	_u.mutation.AddTicketIDs(ids...)
	return _u
}

// AddTickets adds the "tickets" edges to the LotoTicket entity.
func (_u *LotoGameUpdate) AddTickets(v ...*LotoTicket) *LotoGameUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTicketIDs(ids...)
}

// AddPrizeIDs adds the "prizes" edge to the LotoPrize entity by IDs.
func (_u *LotoGameUpdate) AddPrizeIDs(ids ...string) *LotoGameUpdate {
	_u.mutation.AddPrizeIDs(ids...)
	return _u
}

// AddPrizes adds the "prizes" edges to the LotoPrize entity.
func (_u *LotoGameUpdate) AddPrizes(v ...*LotoPrize) *LotoGameUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrizeIDs(ids...)
}

// Mutation returns the LotoGameMutation object of the builder.
func (_u *LotoGameUpdate) Mutation() *LotoGameMutation {
	return _u.mutation
}

// ClearPlayers clears all "players" edges to the LotoPlayer entity.
func (_u *LotoGameUpdate) ClearPlayers() *LotoGameUpdate {
	_u.mutation.ClearPlayers()
	return _u
}

// RemovePlayerIDs removes the "players" edge to LotoPlayer entities by IDs.
func (_u *LotoGameUpdate) RemovePlayerIDs(ids ...string) *LotoGameUpdate {
	_u.mutation.RemovePlayerIDs(ids...)
	return _u
}

// RemovePlayers removes "players" edges to LotoPlayer entities.
func (_u *LotoGameUpdate) RemovePlayers(v ...*LotoPlayer) *LotoGameUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlayerIDs(ids...)
}

// ClearTickets clears all "tickets" edges to the LotoTicket entity.
func (_u *LotoGameUpdate) ClearTickets() *LotoGameUpdate {
	_u.mutation.ClearTickets()
	return _u
}

// RemoveTicketIDs removes the "tickets" edge to LotoTicket entities by IDs.
func (_u *LotoGameUpdate) RemoveTicketIDs(ids ...string) *LotoGameUpdate {
	_u.mutation.RemoveTicketIDs(ids...)
	return _u
}

// RemoveTickets removes "tickets" edges to LotoTicket entities.
func (_u *LotoGameUpdate) RemoveTickets(v ...*LotoTicket) *LotoGameUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTicketIDs(ids...)
}

// ClearPrizes clears all "prizes" edges to the LotoPrize entity.
func (_u *LotoGameUpdate) ClearPrizes() *LotoGameUpdate {
	_u.mutation.ClearPrizes()
	return _u
}

// RemovePrizeIDs removes the "prizes" edge to LotoPrize entities by IDs.
func (_u *LotoGameUpdate) RemovePrizeIDs(ids ...string) *LotoGameUpdate {
	_u.mutation.RemovePrizeIDs(ids...)
	return _u
}

// RemovePrizes removes "prizes" edges to LotoPrize entities.
func (_u *LotoGameUpdate) RemovePrizes(v ...*LotoPrize) *LotoGameUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrizeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotoGameUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotoGameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotoGameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotoGameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotoGameUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotogame.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotoGameUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := lotogame.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotoGame.name": %w`, err)}
		}
	}
	return nil
}

func (_u *LotoGameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotogame.Table, lotogame.Columns, sqlgraph.NewFieldSpec(lotogame.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(lotogame.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(lotogame.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(lotogame.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TicketPrice(); ok {
		_spec.SetField(lotogame.FieldTicketPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTicketPrice(); ok {
		_spec.AddField(lotogame.FieldTicketPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CooldownMinutes(); ok {
		_spec.SetField(lotogame.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownMinutes(); ok {
		_spec.AddField(lotogame.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxTicketsPerPurchase(); ok {
		_spec.SetField(lotogame.FieldMaxTicketsPerPurchase, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTicketsPerPurchase(); ok {
		_spec.AddField(lotogame.FieldMaxTicketsPerPurchase, field.TypeInt, value)
	}
	if _u.mutation.MaxTicketsPerPurchaseCleared() {
		_spec.ClearField(lotogame.FieldMaxTicketsPerPurchase, field.TypeInt)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(lotogame.FieldMessageID, field.TypeString, value)
	}
	if _u.mutation.MessageIDCleared() {
		_spec.ClearField(lotogame.FieldMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(lotogame.FieldChannelID, field.TypeString, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(lotogame.FieldChannelID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotogame.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PlayersTable,
			Columns: []string{lotogame.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlayersIDs(); len(nodes) > 0 && !_u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PlayersTable,
			Columns: []string{lotogame.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PlayersTable,
			Columns: []string{lotogame.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.TicketsTable,
			Columns: []string{lotogame.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lototicket.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !_u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.TicketsTable,
			Columns: []string{lotogame.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lototicket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.TicketsTable,
			Columns: []string{lotogame.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lototicket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrizesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PrizesTable,
			Columns: []string{lotogame.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoprize.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrizesIDs(); len(nodes) > 0 && !_u.mutation.PrizesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PrizesTable,
			Columns: []string{lotogame.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoprize.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrizesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PrizesTable,
			Columns: []string{lotogame.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoprize.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotogame.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotoGameUpdateOne is the builder for updating a single LotoGame entity.
type LotoGameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotoGameMutation
}

// SetGuildID sets the "guild_id" field.
func (_u *LotoGameUpdateOne) SetGuildID(v string) *LotoGameUpdateOne {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *LotoGameUpdateOne) SetNillableGuildID(v *string) *LotoGameUpdateOne {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LotoGameUpdateOne) SetName(v string) *LotoGameUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LotoGameUpdateOne) SetNillableName(v *string) *LotoGameUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *LotoGameUpdateOne) SetActive(v bool) *LotoGameUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *LotoGameUpdateOne) SetNillableActive(v *bool) *LotoGameUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetTicketPrice sets the "ticket_price" field.
func (_u *LotoGameUpdateOne) SetTicketPrice(v int) *LotoGameUpdateOne {
	_u.mutation.ResetTicketPrice()
	_u.mutation.SetTicketPrice(v)
	return _u
}

// SetNillableTicketPrice sets the "ticket_price" field if the given value is not nil.
func (_u *LotoGameUpdateOne) SetNillableTicketPrice(v *int) *LotoGameUpdateOne {
	if v != nil {
		_u.SetTicketPrice(*v)
	}
	return _u
}

// AddTicketPrice adds value to the "ticket_price" field.
func (_u *LotoGameUpdateOne) AddTicketPrice(v int) *LotoGameUpdateOne {
	_u.mutation.AddTicketPrice(v)
	return _u
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (_u *LotoGameUpdateOne) SetCooldownMinutes(v int) *LotoGameUpdateOne {
	_u.mutation.ResetCooldownMinutes()
	_u.mutation.SetCooldownMinutes(v)
	return _u
}

// SetNillableCooldownMinutes sets the "cooldown_minutes" field if the given value is not nil.
func (_u *LotoGameUpdateOne) SetNillableCooldownMinutes(v *int) *LotoGameUpdateOne {
	if v != nil {
		_u.SetCooldownMinutes(*v)
	}
	return _u
}

// AddCooldownMinutes adds value to the "cooldown_minutes" field.
func (_u *LotoGameUpdateOne) AddCooldownMinutes(v int) *LotoGameUpdateOne {
	_u.mutation.AddCooldownMinutes(v)
	return _u
}

// SetMaxTicketsPerPurchase sets the "max_tickets_per_purchase" field.
func (_u *LotoGameUpdateOne) SetMaxTicketsPerPurchase(v int) *LotoGameUpdateOne {
	_u.mutation.ResetMaxTicketsPerPurchase()
	_u.mutation.SetMaxTicketsPerPurchase(v)
	return _u
}

// SetNillableMaxTicketsPerPurchase sets the "max_tickets_per_purchase" field if the given value is not nil.
func (_u *LotoGameUpdateOne) SetNillableMaxTicketsPerPurchase(v *int) *LotoGameUpdateOne {
	if v != nil {
		_u.SetMaxTicketsPerPurchase(*v)
	}
	return _u
}

// AddMaxTicketsPerPurchase adds value to the "max_tickets_per_purchase" field.
func (_u *LotoGameUpdateOne) AddMaxTicketsPerPurchase(v int) *LotoGameUpdateOne {
	_u.mutation.AddMaxTicketsPerPurchase(v)
	return _u
}

// ClearMaxTicketsPerPurchase clears the value of the "max_tickets_per_purchase" field.
func (_u *LotoGameUpdateOne) ClearMaxTicketsPerPurchase() *LotoGameUpdateOne {
	_u.mutation.ClearMaxTicketsPerPurchase()
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *LotoGameUpdateOne) SetMessageID(v string) *LotoGameUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *LotoGameUpdateOne) SetNillableMessageID(v *string) *LotoGameUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// ClearMessageID clears the value of the "message_id" field.
func (_u *LotoGameUpdateOne) ClearMessageID() *LotoGameUpdateOne {
	_u.mutation.ClearMessageID()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *LotoGameUpdateOne) SetChannelID(v string) *LotoGameUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *LotoGameUpdateOne) SetNillableChannelID(v *string) *LotoGameUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *LotoGameUpdateOne) ClearChannelID() *LotoGameUpdateOne {
	_u.mutation.ClearChannelID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotoGameUpdateOne) SetUpdatedAt(v time.Time) *LotoGameUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPlayerIDs adds the "players" edge to the LotoPlayer entity by IDs.
func (_u *LotoGameUpdateOne) AddPlayerIDs(ids ...string) *LotoGameUpdateOne {
	_u.mutation.AddPlayerIDs(ids...)
	return _u
}

// AddPlayers adds the "players" edges to the LotoPlayer entity.
func (_u *LotoGameUpdateOne) AddPlayers(v ...*LotoPlayer) *LotoGameUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlayerIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the LotoTicket entity by IDs.
func (_u *LotoGameUpdateOne) AddTicketIDs(ids ...string) *LotoGameUpdateOne {
	_u.mutation.AddTicketIDs(ids...)
	return _u
}

// AddTickets adds the "tickets" edges to the LotoTicket entity.
func (_u *LotoGameUpdateOne) AddTickets(v ...*LotoTicket) *LotoGameUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTicketIDs(ids...)
}

// AddPrizeIDs adds the "prizes" edge to the LotoPrize entity by IDs.
func (_u *LotoGameUpdateOne) AddPrizeIDs(ids ...string) *LotoGameUpdateOne {
	_u.mutation.AddPrizeIDs(ids...)
	return _u
}

// AddPrizes adds the "prizes" edges to the LotoPrize entity.
func (_u *LotoGameUpdateOne) AddPrizes(v ...*LotoPrize) *LotoGameUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPrizeIDs(ids...)
}

// Mutation returns the LotoGameMutation object of the builder.
func (_u *LotoGameUpdateOne) Mutation() *LotoGameMutation {
	return _u.mutation
}

// ClearPlayers clears all "players" edges to the LotoPlayer entity.
func (_u *LotoGameUpdateOne) ClearPlayers() *LotoGameUpdateOne {
	_u.mutation.ClearPlayers()
	return _u
}

// RemovePlayerIDs removes the "players" edge to LotoPlayer entities by IDs.
func (_u *LotoGameUpdateOne) RemovePlayerIDs(ids ...string) *LotoGameUpdateOne {
	_u.mutation.RemovePlayerIDs(ids...)
	return _u
}

// RemovePlayers removes "players" edges to LotoPlayer entities.
func (_u *LotoGameUpdateOne) RemovePlayers(v ...*LotoPlayer) *LotoGameUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlayerIDs(ids...)
}

// ClearTickets clears all "tickets" edges to the LotoTicket entity.
func (_u *LotoGameUpdateOne) ClearTickets() *LotoGameUpdateOne {
	_u.mutation.ClearTickets()
	return _u
}

// RemoveTicketIDs removes the "tickets" edge to LotoTicket entities by IDs.
func (_u *LotoGameUpdateOne) RemoveTicketIDs(ids ...string) *LotoGameUpdateOne {
	_u.mutation.RemoveTicketIDs(ids...)
	return _u
}

// RemoveTickets removes "tickets" edges to LotoTicket entities.
func (_u *LotoGameUpdateOne) RemoveTickets(v ...*LotoTicket) *LotoGameUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTicketIDs(ids...)
}

// ClearPrizes clears all "prizes" edges to the LotoPrize entity.
func (_u *LotoGameUpdateOne) ClearPrizes() *LotoGameUpdateOne {
	_u.mutation.ClearPrizes()
	return _u
}

// RemovePrizeIDs removes the "prizes" edge to LotoPrize entities by IDs.
func (_u *LotoGameUpdateOne) RemovePrizeIDs(ids ...string) *LotoGameUpdateOne {
	_u.mutation.RemovePrizeIDs(ids...)
	return _u
}

// RemovePrizes removes "prizes" edges to LotoPrize entities.
func (_u *LotoGameUpdateOne) RemovePrizes(v ...*LotoPrize) *LotoGameUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePrizeIDs(ids...)
}

// Where appends a list predicates to the LotoGameUpdate builder.
func (_u *LotoGameUpdateOne) Where(ps ...predicate.LotoGame) *LotoGameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotoGameUpdateOne) Select(field string, fields ...string) *LotoGameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotoGame entity.
func (_u *LotoGameUpdateOne) Save(ctx context.Context) (*LotoGame, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotoGameUpdateOne) SaveX(ctx context.Context) *LotoGame {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotoGameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotoGameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotoGameUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotogame.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotoGameUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := lotogame.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotoGame.name": %w`, err)}
		}
	}
	return nil
}

func (_u *LotoGameUpdateOne) sqlSave(ctx context.Context) (_node *LotoGame, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotogame.Table, lotogame.Columns, sqlgraph.NewFieldSpec(lotogame.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotoGame.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotogame.FieldID)
		for _, f := range fields {
			if !lotogame.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotogame.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(lotogame.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(lotogame.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(lotogame.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TicketPrice(); ok {
		_spec.SetField(lotogame.FieldTicketPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTicketPrice(); ok {
		_spec.AddField(lotogame.FieldTicketPrice, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CooldownMinutes(); ok {
		_spec.SetField(lotogame.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownMinutes(); ok {
		_spec.AddField(lotogame.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxTicketsPerPurchase(); ok {
		_spec.SetField(lotogame.FieldMaxTicketsPerPurchase, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTicketsPerPurchase(); ok {
		_spec.AddField(lotogame.FieldMaxTicketsPerPurchase, field.TypeInt, value)
	}
	if _u.mutation.MaxTicketsPerPurchaseCleared() {
		_spec.ClearField(lotogame.FieldMaxTicketsPerPurchase, field.TypeInt)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(lotogame.FieldMessageID, field.TypeString, value)
	}
	if _u.mutation.MessageIDCleared() {
		_spec.ClearField(lotogame.FieldMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(lotogame.FieldChannelID, field.TypeString, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(lotogame.FieldChannelID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotogame.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PlayersTable,
			Columns: []string{lotogame.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlayersIDs(); len(nodes) > 0 && !_u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PlayersTable,
			Columns: []string{lotogame.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PlayersTable,
			Columns: []string{lotogame.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoplayer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.TicketsTable,
			Columns: []string{lotogame.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lototicket.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !_u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.TicketsTable,
			Columns: []string{lotogame.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lototicket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.TicketsTable,
			Columns: []string{lotogame.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lototicket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PrizesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PrizesTable,
			Columns: []string{lotogame.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoprize.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPrizesIDs(); len(nodes) > 0 && !_u.mutation.PrizesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PrizesTable,
			Columns: []string{lotogame.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoprize.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PrizesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotogame.PrizesTable,
			Columns: []string{lotogame.PrizesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotoprize.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LotoGame{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotogame.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
