// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/quizanswer"
	"Eve/internal/database/ent/quizquestion"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// QuizAnswer is the model entity for the QuizAnswer schema.
type QuizAnswer struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// AnswerText holds the value of the "answer_text" field.
	AnswerText string `json:"answer_text,omitempty"`
	// IsValid holds the value of the "is_valid" field.
	IsValid bool `json:"is_valid,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QuizAnswerQuery when eager-loading is set.
	Edges                 QuizAnswerEdges `json:"edges"`
	quiz_question_answers *string
	selectValues          sql.SelectValues
}

// QuizAnswerEdges holds the relations/edges for other nodes in the graph.
type QuizAnswerEdges struct {
	// Question holds the value of the question edge.
	Question *QuizQuestion `json:"question,omitempty"`
	// UserAnswers holds the value of the user_answers edge.
	UserAnswers []*QuizUserAnswer `json:"user_answers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QuizAnswerEdges) QuestionOrErr() (*QuizQuestion, error) {
	if e.Question != nil {
		return e.Question, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: quizquestion.Label}
	}
	return nil, &NotLoadedError{edge: "question"}
}

// UserAnswersOrErr returns the UserAnswers value or an error if the edge
// was not loaded in eager-loading.
func (e QuizAnswerEdges) UserAnswersOrErr() ([]*QuizUserAnswer, error) {
	if e.loadedTypes[1] {
		return e.UserAnswers, nil
	}
	return nil, &NotLoadedError{edge: "user_answers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QuizAnswer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quizanswer.FieldIsValid:
			values[i] = new(sql.NullBool)
		case quizanswer.FieldID, quizanswer.FieldAnswerText:
			values[i] = new(sql.NullString)
		case quizanswer.FieldCreatedAt, quizanswer.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case quizanswer.ForeignKeys[0]: // quiz_question_answers
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QuizAnswer fields.
func (_m *QuizAnswer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quizanswer.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case quizanswer.FieldAnswerText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field answer_text", values[i])
			} else if value.Valid {
				_m.AnswerText = value.String
			}
		case quizanswer.FieldIsValid:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_valid", values[i])
			} else if value.Valid {
				_m.IsValid = value.Bool
			}
		case quizanswer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case quizanswer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case quizanswer.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quiz_question_answers", values[i])
			} else if value.Valid {
				_m.quiz_question_answers = new(string)
				*_m.quiz_question_answers = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QuizAnswer.
// This includes values selected through modifiers, order, etc.
func (_m *QuizAnswer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuestion queries the "question" edge of the QuizAnswer entity.
func (_m *QuizAnswer) QueryQuestion() *QuizQuestionQuery {
	return NewQuizAnswerClient(_m.config).QueryQuestion(_m)
}

// QueryUserAnswers queries the "user_answers" edge of the QuizAnswer entity.
func (_m *QuizAnswer) QueryUserAnswers() *QuizUserAnswerQuery {
	return NewQuizAnswerClient(_m.config).QueryUserAnswers(_m)
}

// Update returns a builder for updating this QuizAnswer.
// Note that you need to call QuizAnswer.Unwrap() before calling this method if this QuizAnswer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QuizAnswer) Update() *QuizAnswerUpdateOne {
	return NewQuizAnswerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QuizAnswer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QuizAnswer) Unwrap() *QuizAnswer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QuizAnswer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QuizAnswer) String() string {
	var builder strings.Builder
	builder.WriteString("QuizAnswer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("answer_text=")
	builder.WriteString(_m.AnswerText)
	builder.WriteString(", ")
	builder.WriteString("is_valid=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsValid))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// QuizAnswers is a parsable slice of QuizAnswer.
type QuizAnswers []*QuizAnswer
