// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/predicate"
	"Eve/internal/database/ent/quizanswer"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizAnswerDelete is the builder for deleting a QuizAnswer entity.
type QuizAnswerDelete struct {
	config
	hooks    []Hook
	mutation *QuizAnswerMutation
}

// Where appends a list predicates to the QuizAnswerDelete builder.
func (_d *QuizAnswerDelete) Where(ps ...predicate.QuizAnswer) *QuizAnswerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *QuizAnswerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuizAnswerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *QuizAnswerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(quizanswer.Table, sqlgraph.NewFieldSpec(quizanswer.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// QuizAnswerDeleteOne is the builder for deleting a single QuizAnswer entity.
type QuizAnswerDeleteOne struct {
	_d *QuizAnswerDelete
}

// Where appends a list predicates to the QuizAnswerDelete builder.
func (_d *QuizAnswerDeleteOne) Where(ps ...predicate.QuizAnswer) *QuizAnswerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *QuizAnswerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{quizanswer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuizAnswerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
