// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/quiz"
	"Eve/internal/database/ent/quizquestion"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// QuizQuestion is the model entity for the QuizQuestion schema.
type QuizQuestion struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// QuestionText holds the value of the "question_text" field.
	QuestionText string `json:"question_text,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QuizQuestionQuery when eager-loading is set.
	Edges          QuizQuestionEdges `json:"edges"`
	quiz_questions *string
	selectValues   sql.SelectValues
}

// QuizQuestionEdges holds the relations/edges for other nodes in the graph.
type QuizQuestionEdges struct {
	// Quiz holds the value of the quiz edge.
	Quiz *Quiz `json:"quiz,omitempty"`
	// Answers holds the value of the answers edge.
	Answers []*QuizAnswer `json:"answers,omitempty"`
	// UserAnswers holds the value of the user_answers edge.
	UserAnswers []*QuizUserAnswer `json:"user_answers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// QuizOrErr returns the Quiz value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QuizQuestionEdges) QuizOrErr() (*Quiz, error) {
	if e.Quiz != nil {
		return e.Quiz, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: quiz.Label}
	}
	return nil, &NotLoadedError{edge: "quiz"}
}

// AnswersOrErr returns the Answers value or an error if the edge
// was not loaded in eager-loading.
func (e QuizQuestionEdges) AnswersOrErr() ([]*QuizAnswer, error) {
	if e.loadedTypes[1] {
		return e.Answers, nil
	}
	return nil, &NotLoadedError{edge: "answers"}
}

// UserAnswersOrErr returns the UserAnswers value or an error if the edge
// was not loaded in eager-loading.
func (e QuizQuestionEdges) UserAnswersOrErr() ([]*QuizUserAnswer, error) {
	if e.loadedTypes[2] {
		return e.UserAnswers, nil
	}
	return nil, &NotLoadedError{edge: "user_answers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QuizQuestion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quizquestion.FieldID, quizquestion.FieldQuestionText:
			values[i] = new(sql.NullString)
		case quizquestion.FieldCreatedAt, quizquestion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case quizquestion.ForeignKeys[0]: // quiz_questions
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QuizQuestion fields.
func (_m *QuizQuestion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quizquestion.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case quizquestion.FieldQuestionText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field question_text", values[i])
			} else if value.Valid {
				_m.QuestionText = value.String
			}
		case quizquestion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case quizquestion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case quizquestion.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quiz_questions", values[i])
			} else if value.Valid {
				_m.quiz_questions = new(string)
				*_m.quiz_questions = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QuizQuestion.
// This includes values selected through modifiers, order, etc.
func (_m *QuizQuestion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuiz queries the "quiz" edge of the QuizQuestion entity.
func (_m *QuizQuestion) QueryQuiz() *QuizQuery {
	return NewQuizQuestionClient(_m.config).QueryQuiz(_m)
}

// QueryAnswers queries the "answers" edge of the QuizQuestion entity.
func (_m *QuizQuestion) QueryAnswers() *QuizAnswerQuery {
	return NewQuizQuestionClient(_m.config).QueryAnswers(_m)
}

// QueryUserAnswers queries the "user_answers" edge of the QuizQuestion entity.
func (_m *QuizQuestion) QueryUserAnswers() *QuizUserAnswerQuery {
	return NewQuizQuestionClient(_m.config).QueryUserAnswers(_m)
}

// Update returns a builder for updating this QuizQuestion.
// Note that you need to call QuizQuestion.Unwrap() before calling this method if this QuizQuestion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QuizQuestion) Update() *QuizQuestionUpdateOne {
	return NewQuizQuestionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QuizQuestion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QuizQuestion) Unwrap() *QuizQuestion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QuizQuestion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QuizQuestion) String() string {
	var builder strings.Builder
	builder.WriteString("QuizQuestion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("question_text=")
	builder.WriteString(_m.QuestionText)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// QuizQuestions is a parsable slice of QuizQuestion.
type QuizQuestions []*QuizQuestion
