// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/quiz"
	"Eve/internal/database/ent/quizquestion"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizCreate is the builder for creating a Quiz entity.
type QuizCreate struct {
	config
	mutation *QuizMutation
	hooks    []Hook
}

// SetAuthorID sets the "author_id" field.
func (_c *QuizCreate) SetAuthorID(v string) *QuizCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *QuizCreate) SetTitle(v string) *QuizCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuizCreate) SetCreatedAt(v time.Time) *QuizCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuizCreate) SetNillableCreatedAt(v *time.Time) *QuizCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuizCreate) SetUpdatedAt(v time.Time) *QuizCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuizCreate) SetNillableUpdatedAt(v *time.Time) *QuizCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuizCreate) SetID(v string) *QuizCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddQuestionIDs adds the "questions" edge to the QuizQuestion entity by IDs.
func (_c *QuizCreate) AddQuestionIDs(ids ...string) *QuizCreate {
	_c.mutation.AddQuestionIDs(ids...)
	return _c
}

// AddQuestions adds the "questions" edges to the QuizQuestion entity.
func (_c *QuizCreate) AddQuestions(v ...*QuizQuestion) *QuizCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddQuestionIDs(ids...)
}

// Mutation returns the QuizMutation object of the builder.
func (_c *QuizCreate) Mutation() *QuizMutation {
	return _c.mutation
}

// Save creates the Quiz in the database.
func (_c *QuizCreate) Save(ctx context.Context) (*Quiz, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuizCreate) SaveX(ctx context.Context) *Quiz {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuizCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuizCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuizCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quiz.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := quiz.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuizCreate) check() error {
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "Quiz.author_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Quiz.title"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Quiz.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Quiz.updated_at"`)}
	}
	return nil
}

func (_c *QuizCreate) sqlSave(ctx context.Context) (*Quiz, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Quiz.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuizCreate) createSpec() (*Quiz, *sqlgraph.CreateSpec) {
	var (
		_node = &Quiz{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quiz.Table, sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AuthorID(); ok {
		_spec.SetField(quiz.FieldAuthorID, field.TypeString, value)
		_node.AuthorID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(quiz.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quiz.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(quiz.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.QuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quiz.QuestionsTable,
			Columns: []string{quiz.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizquestion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuizCreateBulk is the builder for creating many Quiz entities in bulk.
type QuizCreateBulk struct {
	config
	err      error
	builders []*QuizCreate
}

// Save creates the Quiz entities in the database.
func (_c *QuizCreateBulk) Save(ctx context.Context) ([]*Quiz, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Quiz, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuizMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuizCreateBulk) SaveX(ctx context.Context) []*Quiz {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuizCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuizCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
