// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/activequiz"
	"Eve/internal/database/ent/predicate"
	"Eve/internal/database/ent/quizuseranswer"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizUserAnswerQuery is the builder for querying QuizUserAnswer entities.
type QuizUserAnswerQuery struct {
	config
	ctx            *QueryContext
	order          []quizuseranswer.OrderOption
	inters         []Interceptor
	predicates     []predicate.QuizUserAnswer
	withActiveQuiz *ActiveQuizQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuizUserAnswerQuery builder.
func (_q *QuizUserAnswerQuery) Where(ps ...predicate.QuizUserAnswer) *QuizUserAnswerQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *QuizUserAnswerQuery) Limit(limit int) *QuizUserAnswerQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *QuizUserAnswerQuery) Offset(offset int) *QuizUserAnswerQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *QuizUserAnswerQuery) Unique(unique bool) *QuizUserAnswerQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *QuizUserAnswerQuery) Order(o ...quizuseranswer.OrderOption) *QuizUserAnswerQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryActiveQuiz chains the current query on the "active_quiz" edge.
func (_q *QuizUserAnswerQuery) QueryActiveQuiz() *ActiveQuizQuery {
	query := (&ActiveQuizClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quizuseranswer.Table, quizuseranswer.FieldID, selector),
			sqlgraph.To(activequiz.Table, activequiz.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, quizuseranswer.ActiveQuizTable, quizuseranswer.ActiveQuizColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QuizUserAnswer entity from the query.
// Returns a *NotFoundError when no QuizUserAnswer was found.
func (_q *QuizUserAnswerQuery) First(ctx context.Context) (*QuizUserAnswer, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{quizuseranswer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *QuizUserAnswerQuery) FirstX(ctx context.Context) *QuizUserAnswer {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuizUserAnswer ID from the query.
// Returns a *NotFoundError when no QuizUserAnswer ID was found.
func (_q *QuizUserAnswerQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{quizuseranswer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *QuizUserAnswerQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuizUserAnswer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuizUserAnswer entity is found.
// Returns a *NotFoundError when no QuizUserAnswer entities are found.
func (_q *QuizUserAnswerQuery) Only(ctx context.Context) (*QuizUserAnswer, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{quizuseranswer.Label}
	default:
		return nil, &NotSingularError{quizuseranswer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *QuizUserAnswerQuery) OnlyX(ctx context.Context) *QuizUserAnswer {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuizUserAnswer ID in the query.
// Returns a *NotSingularError when more than one QuizUserAnswer ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *QuizUserAnswerQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{quizuseranswer.Label}
	default:
		err = &NotSingularError{quizuseranswer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *QuizUserAnswerQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuizUserAnswers.
func (_q *QuizUserAnswerQuery) All(ctx context.Context) ([]*QuizUserAnswer, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QuizUserAnswer, *QuizUserAnswerQuery]()
	return withInterceptors[[]*QuizUserAnswer](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *QuizUserAnswerQuery) AllX(ctx context.Context) []*QuizUserAnswer {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuizUserAnswer IDs.
func (_q *QuizUserAnswerQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(quizuseranswer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *QuizUserAnswerQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *QuizUserAnswerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*QuizUserAnswerQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *QuizUserAnswerQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *QuizUserAnswerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *QuizUserAnswerQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuizUserAnswerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *QuizUserAnswerQuery) Clone() *QuizUserAnswerQuery {
	if _q == nil {
		return nil
	}
	return &QuizUserAnswerQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]quizuseranswer.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.QuizUserAnswer{}, _q.predicates...),
		withActiveQuiz: _q.withActiveQuiz.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithActiveQuiz tells the query-builder to eager-load the nodes that are connected to
// the "active_quiz" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuizUserAnswerQuery) WithActiveQuiz(opts ...func(*ActiveQuizQuery)) *QuizUserAnswerQuery {
	query := (&ActiveQuizClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withActiveQuiz = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ActiveQuizID string `json:"active_quiz_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuizUserAnswer.Query().
//		GroupBy(quizuseranswer.FieldActiveQuizID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *QuizUserAnswerQuery) GroupBy(field string, fields ...string) *QuizUserAnswerGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuizUserAnswerGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = quizuseranswer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ActiveQuizID string `json:"active_quiz_id,omitempty"`
//	}
//
//	client.QuizUserAnswer.Query().
//		Select(quizuseranswer.FieldActiveQuizID).
//		Scan(ctx, &v)
func (_q *QuizUserAnswerQuery) Select(fields ...string) *QuizUserAnswerSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &QuizUserAnswerSelect{QuizUserAnswerQuery: _q}
	sbuild.label = quizuseranswer.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuizUserAnswerSelect configured with the given aggregations.
func (_q *QuizUserAnswerQuery) Aggregate(fns ...AggregateFunc) *QuizUserAnswerSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *QuizUserAnswerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !quizuseranswer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *QuizUserAnswerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuizUserAnswer, error) {
	var (
		nodes       = []*QuizUserAnswer{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withActiveQuiz != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuizUserAnswer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuizUserAnswer{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withActiveQuiz; query != nil {
		if err := _q.loadActiveQuiz(ctx, query, nodes, nil,
			func(n *QuizUserAnswer, e *ActiveQuiz) { n.Edges.ActiveQuiz = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *QuizUserAnswerQuery) loadActiveQuiz(ctx context.Context, query *ActiveQuizQuery, nodes []*QuizUserAnswer, init func(*QuizUserAnswer), assign func(*QuizUserAnswer, *ActiveQuiz)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*QuizUserAnswer)
	for i := range nodes {
		fk := nodes[i].ActiveQuizID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(activequiz.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "active_quiz_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *QuizUserAnswerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *QuizUserAnswerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(quizuseranswer.Table, quizuseranswer.Columns, sqlgraph.NewFieldSpec(quizuseranswer.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quizuseranswer.FieldID)
		for i := range fields {
			if fields[i] != quizuseranswer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withActiveQuiz != nil {
			_spec.Node.AddColumnOnce(quizuseranswer.FieldActiveQuizID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *QuizUserAnswerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(quizuseranswer.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = quizuseranswer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QuizUserAnswerGroupBy is the group-by builder for QuizUserAnswer entities.
type QuizUserAnswerGroupBy struct {
	selector
	build *QuizUserAnswerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *QuizUserAnswerGroupBy) Aggregate(fns ...AggregateFunc) *QuizUserAnswerGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *QuizUserAnswerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuizUserAnswerQuery, *QuizUserAnswerGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *QuizUserAnswerGroupBy) sqlScan(ctx context.Context, root *QuizUserAnswerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuizUserAnswerSelect is the builder for selecting fields of QuizUserAnswer entities.
type QuizUserAnswerSelect struct {
	*QuizUserAnswerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *QuizUserAnswerSelect) Aggregate(fns ...AggregateFunc) *QuizUserAnswerSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *QuizUserAnswerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuizUserAnswerQuery, *QuizUserAnswerSelect](ctx, _s.QuizUserAnswerQuery, _s, _s.inters, v)
}

func (_s *QuizUserAnswerSelect) sqlScan(ctx context.Context, root *QuizUserAnswerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
