// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/activequiz"
	"Eve/internal/database/ent/predicate"
	"Eve/internal/database/ent/quizquestion"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizQuestionUpdate is the builder for updating QuizQuestion entities.
type QuizQuestionUpdate struct {
	config
	hooks    []Hook
	mutation *QuizQuestionMutation
}

// Where appends a list predicates to the QuizQuestionUpdate builder.
func (_u *QuizQuestionUpdate) Where(ps ...predicate.QuizQuestion) *QuizQuestionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuestion sets the "question" field.
func (_u *QuizQuestionUpdate) SetQuestion(v string) *QuizQuestionUpdate {
	_u.mutation.SetQuestion(v)
	return _u
}

// SetNillableQuestion sets the "question" field if the given value is not nil.
func (_u *QuizQuestionUpdate) SetNillableQuestion(v *string) *QuizQuestionUpdate {
	if v != nil {
		_u.SetQuestion(*v)
	}
	return _u
}

// SetGoodAnswer sets the "good_answer" field.
func (_u *QuizQuestionUpdate) SetGoodAnswer(v string) *QuizQuestionUpdate {
	_u.mutation.SetGoodAnswer(v)
	return _u
}

// SetNillableGoodAnswer sets the "good_answer" field if the given value is not nil.
func (_u *QuizQuestionUpdate) SetNillableGoodAnswer(v *string) *QuizQuestionUpdate {
	if v != nil {
		_u.SetGoodAnswer(*v)
	}
	return _u
}

// SetBadAnswer1 sets the "bad_answer_1" field.
func (_u *QuizQuestionUpdate) SetBadAnswer1(v string) *QuizQuestionUpdate {
	_u.mutation.SetBadAnswer1(v)
	return _u
}

// SetNillableBadAnswer1 sets the "bad_answer_1" field if the given value is not nil.
func (_u *QuizQuestionUpdate) SetNillableBadAnswer1(v *string) *QuizQuestionUpdate {
	if v != nil {
		_u.SetBadAnswer1(*v)
	}
	return _u
}

// SetBadAnswer2 sets the "bad_answer_2" field.
func (_u *QuizQuestionUpdate) SetBadAnswer2(v string) *QuizQuestionUpdate {
	_u.mutation.SetBadAnswer2(v)
	return _u
}

// SetNillableBadAnswer2 sets the "bad_answer_2" field if the given value is not nil.
func (_u *QuizQuestionUpdate) SetNillableBadAnswer2(v *string) *QuizQuestionUpdate {
	if v != nil {
		_u.SetBadAnswer2(*v)
	}
	return _u
}

// SetBadAnswer3 sets the "bad_answer_3" field.
func (_u *QuizQuestionUpdate) SetBadAnswer3(v string) *QuizQuestionUpdate {
	_u.mutation.SetBadAnswer3(v)
	return _u
}

// SetNillableBadAnswer3 sets the "bad_answer_3" field if the given value is not nil.
func (_u *QuizQuestionUpdate) SetNillableBadAnswer3(v *string) *QuizQuestionUpdate {
	if v != nil {
		_u.SetBadAnswer3(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *QuizQuestionUpdate) SetCategory(v string) *QuizQuestionUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *QuizQuestionUpdate) SetNillableCategory(v *string) *QuizQuestionUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetDifficulty sets the "difficulty" field.
func (_u *QuizQuestionUpdate) SetDifficulty(v string) *QuizQuestionUpdate {
	_u.mutation.SetDifficulty(v)
	return _u
}

// SetNillableDifficulty sets the "difficulty" field if the given value is not nil.
func (_u *QuizQuestionUpdate) SetNillableDifficulty(v *string) *QuizQuestionUpdate {
	if v != nil {
		_u.SetDifficulty(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *QuizQuestionUpdate) SetAuthorID(v string) *QuizQuestionUpdate {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *QuizQuestionUpdate) SetNillableAuthorID(v *string) *QuizQuestionUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// ClearAuthorID clears the value of the "author_id" field.
func (_u *QuizQuestionUpdate) ClearAuthorID() *QuizQuestionUpdate {
	_u.mutation.ClearAuthorID()
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *QuizQuestionUpdate) SetGuildID(v string) *QuizQuestionUpdate {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *QuizQuestionUpdate) SetNillableGuildID(v *string) *QuizQuestionUpdate {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *QuizQuestionUpdate) SetLastUsedAt(v time.Time) *QuizQuestionUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *QuizQuestionUpdate) SetNillableLastUsedAt(v *time.Time) *QuizQuestionUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *QuizQuestionUpdate) ClearLastUsedAt() *QuizQuestionUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// AddActiveQuizzeIDs adds the "active_quizzes" edge to the ActiveQuiz entity by IDs.
func (_u *QuizQuestionUpdate) AddActiveQuizzeIDs(ids ...string) *QuizQuestionUpdate {
	_u.mutation.AddActiveQuizzeIDs(ids...)
	return _u
}

// AddActiveQuizzes adds the "active_quizzes" edges to the ActiveQuiz entity.
func (_u *QuizQuestionUpdate) AddActiveQuizzes(v ...*ActiveQuiz) *QuizQuestionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActiveQuizzeIDs(ids...)
}

// Mutation returns the QuizQuestionMutation object of the builder.
func (_u *QuizQuestionUpdate) Mutation() *QuizQuestionMutation {
	return _u.mutation
}

// ClearActiveQuizzes clears all "active_quizzes" edges to the ActiveQuiz entity.
func (_u *QuizQuestionUpdate) ClearActiveQuizzes() *QuizQuestionUpdate {
	_u.mutation.ClearActiveQuizzes()
	return _u
}

// RemoveActiveQuizzeIDs removes the "active_quizzes" edge to ActiveQuiz entities by IDs.
func (_u *QuizQuestionUpdate) RemoveActiveQuizzeIDs(ids ...string) *QuizQuestionUpdate {
	_u.mutation.RemoveActiveQuizzeIDs(ids...)
	return _u
}

// RemoveActiveQuizzes removes "active_quizzes" edges to ActiveQuiz entities.
func (_u *QuizQuestionUpdate) RemoveActiveQuizzes(v ...*ActiveQuiz) *QuizQuestionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActiveQuizzeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuizQuestionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuizQuestionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuizQuestionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuizQuestionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuizQuestionUpdate) check() error {
	if v, ok := _u.mutation.Question(); ok {
		if err := quizquestion.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.question": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GoodAnswer(); ok {
		if err := quizquestion.GoodAnswerValidator(v); err != nil {
			return &ValidationError{Name: "good_answer", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.good_answer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BadAnswer1(); ok {
		if err := quizquestion.BadAnswer1Validator(v); err != nil {
			return &ValidationError{Name: "bad_answer_1", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.bad_answer_1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BadAnswer2(); ok {
		if err := quizquestion.BadAnswer2Validator(v); err != nil {
			return &ValidationError{Name: "bad_answer_2", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.bad_answer_2": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BadAnswer3(); ok {
		if err := quizquestion.BadAnswer3Validator(v); err != nil {
			return &ValidationError{Name: "bad_answer_3", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.bad_answer_3": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := quizquestion.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Difficulty(); ok {
		if err := quizquestion.DifficultyValidator(v); err != nil {
			return &ValidationError{Name: "difficulty", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.difficulty": %w`, err)}
		}
	}
	return nil
}

func (_u *QuizQuestionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quizquestion.Table, quizquestion.Columns, sqlgraph.NewFieldSpec(quizquestion.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Question(); ok {
		_spec.SetField(quizquestion.FieldQuestion, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoodAnswer(); ok {
		_spec.SetField(quizquestion.FieldGoodAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.BadAnswer1(); ok {
		_spec.SetField(quizquestion.FieldBadAnswer1, field.TypeString, value)
	}
	if value, ok := _u.mutation.BadAnswer2(); ok {
		_spec.SetField(quizquestion.FieldBadAnswer2, field.TypeString, value)
	}
	if value, ok := _u.mutation.BadAnswer3(); ok {
		_spec.SetField(quizquestion.FieldBadAnswer3, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(quizquestion.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Difficulty(); ok {
		_spec.SetField(quizquestion.FieldDifficulty, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(quizquestion.FieldAuthorID, field.TypeString, value)
	}
	if _u.mutation.AuthorIDCleared() {
		_spec.ClearField(quizquestion.FieldAuthorID, field.TypeString)
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(quizquestion.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(quizquestion.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(quizquestion.FieldLastUsedAt, field.TypeTime)
	}
	if _u.mutation.ActiveQuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizquestion.ActiveQuizzesTable,
			Columns: []string{quizquestion.ActiveQuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activequiz.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActiveQuizzesIDs(); len(nodes) > 0 && !_u.mutation.ActiveQuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizquestion.ActiveQuizzesTable,
			Columns: []string{quizquestion.ActiveQuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activequiz.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActiveQuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizquestion.ActiveQuizzesTable,
			Columns: []string{quizquestion.ActiveQuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activequiz.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quizquestion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuizQuestionUpdateOne is the builder for updating a single QuizQuestion entity.
type QuizQuestionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuizQuestionMutation
}

// SetQuestion sets the "question" field.
func (_u *QuizQuestionUpdateOne) SetQuestion(v string) *QuizQuestionUpdateOne {
	_u.mutation.SetQuestion(v)
	return _u
}

// SetNillableQuestion sets the "question" field if the given value is not nil.
func (_u *QuizQuestionUpdateOne) SetNillableQuestion(v *string) *QuizQuestionUpdateOne {
	if v != nil {
		_u.SetQuestion(*v)
	}
	return _u
}

// SetGoodAnswer sets the "good_answer" field.
func (_u *QuizQuestionUpdateOne) SetGoodAnswer(v string) *QuizQuestionUpdateOne {
	_u.mutation.SetGoodAnswer(v)
	return _u
}

// SetNillableGoodAnswer sets the "good_answer" field if the given value is not nil.
func (_u *QuizQuestionUpdateOne) SetNillableGoodAnswer(v *string) *QuizQuestionUpdateOne {
	if v != nil {
		_u.SetGoodAnswer(*v)
	}
	return _u
}

// SetBadAnswer1 sets the "bad_answer_1" field.
func (_u *QuizQuestionUpdateOne) SetBadAnswer1(v string) *QuizQuestionUpdateOne {
	_u.mutation.SetBadAnswer1(v)
	return _u
}

// SetNillableBadAnswer1 sets the "bad_answer_1" field if the given value is not nil.
func (_u *QuizQuestionUpdateOne) SetNillableBadAnswer1(v *string) *QuizQuestionUpdateOne {
	if v != nil {
		_u.SetBadAnswer1(*v)
	}
	return _u
}

// SetBadAnswer2 sets the "bad_answer_2" field.
func (_u *QuizQuestionUpdateOne) SetBadAnswer2(v string) *QuizQuestionUpdateOne {
	_u.mutation.SetBadAnswer2(v)
	return _u
}

// SetNillableBadAnswer2 sets the "bad_answer_2" field if the given value is not nil.
func (_u *QuizQuestionUpdateOne) SetNillableBadAnswer2(v *string) *QuizQuestionUpdateOne {
	if v != nil {
		_u.SetBadAnswer2(*v)
	}
	return _u
}

// SetBadAnswer3 sets the "bad_answer_3" field.
func (_u *QuizQuestionUpdateOne) SetBadAnswer3(v string) *QuizQuestionUpdateOne {
	_u.mutation.SetBadAnswer3(v)
	return _u
}

// SetNillableBadAnswer3 sets the "bad_answer_3" field if the given value is not nil.
func (_u *QuizQuestionUpdateOne) SetNillableBadAnswer3(v *string) *QuizQuestionUpdateOne {
	if v != nil {
		_u.SetBadAnswer3(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *QuizQuestionUpdateOne) SetCategory(v string) *QuizQuestionUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *QuizQuestionUpdateOne) SetNillableCategory(v *string) *QuizQuestionUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetDifficulty sets the "difficulty" field.
func (_u *QuizQuestionUpdateOne) SetDifficulty(v string) *QuizQuestionUpdateOne {
	_u.mutation.SetDifficulty(v)
	return _u
}

// SetNillableDifficulty sets the "difficulty" field if the given value is not nil.
func (_u *QuizQuestionUpdateOne) SetNillableDifficulty(v *string) *QuizQuestionUpdateOne {
	if v != nil {
		_u.SetDifficulty(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *QuizQuestionUpdateOne) SetAuthorID(v string) *QuizQuestionUpdateOne {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *QuizQuestionUpdateOne) SetNillableAuthorID(v *string) *QuizQuestionUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// ClearAuthorID clears the value of the "author_id" field.
func (_u *QuizQuestionUpdateOne) ClearAuthorID() *QuizQuestionUpdateOne {
	_u.mutation.ClearAuthorID()
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *QuizQuestionUpdateOne) SetGuildID(v string) *QuizQuestionUpdateOne {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *QuizQuestionUpdateOne) SetNillableGuildID(v *string) *QuizQuestionUpdateOne {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *QuizQuestionUpdateOne) SetLastUsedAt(v time.Time) *QuizQuestionUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *QuizQuestionUpdateOne) SetNillableLastUsedAt(v *time.Time) *QuizQuestionUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *QuizQuestionUpdateOne) ClearLastUsedAt() *QuizQuestionUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// AddActiveQuizzeIDs adds the "active_quizzes" edge to the ActiveQuiz entity by IDs.
func (_u *QuizQuestionUpdateOne) AddActiveQuizzeIDs(ids ...string) *QuizQuestionUpdateOne {
	_u.mutation.AddActiveQuizzeIDs(ids...)
	return _u
}

// AddActiveQuizzes adds the "active_quizzes" edges to the ActiveQuiz entity.
func (_u *QuizQuestionUpdateOne) AddActiveQuizzes(v ...*ActiveQuiz) *QuizQuestionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActiveQuizzeIDs(ids...)
}

// Mutation returns the QuizQuestionMutation object of the builder.
func (_u *QuizQuestionUpdateOne) Mutation() *QuizQuestionMutation {
	return _u.mutation
}

// ClearActiveQuizzes clears all "active_quizzes" edges to the ActiveQuiz entity.
func (_u *QuizQuestionUpdateOne) ClearActiveQuizzes() *QuizQuestionUpdateOne {
	_u.mutation.ClearActiveQuizzes()
	return _u
}

// RemoveActiveQuizzeIDs removes the "active_quizzes" edge to ActiveQuiz entities by IDs.
func (_u *QuizQuestionUpdateOne) RemoveActiveQuizzeIDs(ids ...string) *QuizQuestionUpdateOne {
	_u.mutation.RemoveActiveQuizzeIDs(ids...)
	return _u
}

// RemoveActiveQuizzes removes "active_quizzes" edges to ActiveQuiz entities.
func (_u *QuizQuestionUpdateOne) RemoveActiveQuizzes(v ...*ActiveQuiz) *QuizQuestionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActiveQuizzeIDs(ids...)
}

// Where appends a list predicates to the QuizQuestionUpdate builder.
func (_u *QuizQuestionUpdateOne) Where(ps ...predicate.QuizQuestion) *QuizQuestionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuizQuestionUpdateOne) Select(field string, fields ...string) *QuizQuestionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuizQuestion entity.
func (_u *QuizQuestionUpdateOne) Save(ctx context.Context) (*QuizQuestion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuizQuestionUpdateOne) SaveX(ctx context.Context) *QuizQuestion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuizQuestionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuizQuestionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuizQuestionUpdateOne) check() error {
	if v, ok := _u.mutation.Question(); ok {
		if err := quizquestion.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.question": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GoodAnswer(); ok {
		if err := quizquestion.GoodAnswerValidator(v); err != nil {
			return &ValidationError{Name: "good_answer", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.good_answer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BadAnswer1(); ok {
		if err := quizquestion.BadAnswer1Validator(v); err != nil {
			return &ValidationError{Name: "bad_answer_1", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.bad_answer_1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BadAnswer2(); ok {
		if err := quizquestion.BadAnswer2Validator(v); err != nil {
			return &ValidationError{Name: "bad_answer_2", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.bad_answer_2": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BadAnswer3(); ok {
		if err := quizquestion.BadAnswer3Validator(v); err != nil {
			return &ValidationError{Name: "bad_answer_3", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.bad_answer_3": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := quizquestion.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Difficulty(); ok {
		if err := quizquestion.DifficultyValidator(v); err != nil {
			return &ValidationError{Name: "difficulty", err: fmt.Errorf(`ent: validator failed for field "QuizQuestion.difficulty": %w`, err)}
		}
	}
	return nil
}

func (_u *QuizQuestionUpdateOne) sqlSave(ctx context.Context) (_node *QuizQuestion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quizquestion.Table, quizquestion.Columns, sqlgraph.NewFieldSpec(quizquestion.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuizQuestion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quizquestion.FieldID)
		for _, f := range fields {
			if !quizquestion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quizquestion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Question(); ok {
		_spec.SetField(quizquestion.FieldQuestion, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoodAnswer(); ok {
		_spec.SetField(quizquestion.FieldGoodAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.BadAnswer1(); ok {
		_spec.SetField(quizquestion.FieldBadAnswer1, field.TypeString, value)
	}
	if value, ok := _u.mutation.BadAnswer2(); ok {
		_spec.SetField(quizquestion.FieldBadAnswer2, field.TypeString, value)
	}
	if value, ok := _u.mutation.BadAnswer3(); ok {
		_spec.SetField(quizquestion.FieldBadAnswer3, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(quizquestion.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Difficulty(); ok {
		_spec.SetField(quizquestion.FieldDifficulty, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(quizquestion.FieldAuthorID, field.TypeString, value)
	}
	if _u.mutation.AuthorIDCleared() {
		_spec.ClearField(quizquestion.FieldAuthorID, field.TypeString)
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(quizquestion.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(quizquestion.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(quizquestion.FieldLastUsedAt, field.TypeTime)
	}
	if _u.mutation.ActiveQuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizquestion.ActiveQuizzesTable,
			Columns: []string{quizquestion.ActiveQuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activequiz.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActiveQuizzesIDs(); len(nodes) > 0 && !_u.mutation.ActiveQuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizquestion.ActiveQuizzesTable,
			Columns: []string{quizquestion.ActiveQuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activequiz.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActiveQuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizquestion.ActiveQuizzesTable,
			Columns: []string{quizquestion.ActiveQuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activequiz.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &QuizQuestion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quizquestion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
