// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/quiz"
	"Eve/internal/database/ent/quizanswer"
	"Eve/internal/database/ent/quizquestion"
	"Eve/internal/database/ent/quizuseranswer"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuizQuestionCreate is the builder for creating a QuizQuestion entity.
type QuizQuestionCreate struct {
	config
	mutation *QuizQuestionMutation
	hooks    []Hook
}

// SetQuestionText sets the "question_text" field.
func (_c *QuizQuestionCreate) SetQuestionText(v string) *QuizQuestionCreate {
	_c.mutation.SetQuestionText(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuizQuestionCreate) SetCreatedAt(v time.Time) *QuizQuestionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuizQuestionCreate) SetNillableCreatedAt(v *time.Time) *QuizQuestionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuizQuestionCreate) SetUpdatedAt(v time.Time) *QuizQuestionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuizQuestionCreate) SetNillableUpdatedAt(v *time.Time) *QuizQuestionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuizQuestionCreate) SetID(v string) *QuizQuestionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetQuizID sets the "quiz" edge to the Quiz entity by ID.
func (_c *QuizQuestionCreate) SetQuizID(id string) *QuizQuestionCreate {
	_c.mutation.SetQuizID(id)
	return _c
}

// SetQuiz sets the "quiz" edge to the Quiz entity.
func (_c *QuizQuestionCreate) SetQuiz(v *Quiz) *QuizQuestionCreate {
	return _c.SetQuizID(v.ID)
}

// AddAnswerIDs adds the "answers" edge to the QuizAnswer entity by IDs.
func (_c *QuizQuestionCreate) AddAnswerIDs(ids ...string) *QuizQuestionCreate {
	_c.mutation.AddAnswerIDs(ids...)
	return _c
}

// AddAnswers adds the "answers" edges to the QuizAnswer entity.
func (_c *QuizQuestionCreate) AddAnswers(v ...*QuizAnswer) *QuizQuestionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAnswerIDs(ids...)
}

// AddUserAnswerIDs adds the "user_answers" edge to the QuizUserAnswer entity by IDs.
func (_c *QuizQuestionCreate) AddUserAnswerIDs(ids ...string) *QuizQuestionCreate {
	_c.mutation.AddUserAnswerIDs(ids...)
	return _c
}

// AddUserAnswers adds the "user_answers" edges to the QuizUserAnswer entity.
func (_c *QuizQuestionCreate) AddUserAnswers(v ...*QuizUserAnswer) *QuizQuestionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserAnswerIDs(ids...)
}

// Mutation returns the QuizQuestionMutation object of the builder.
func (_c *QuizQuestionCreate) Mutation() *QuizQuestionMutation {
	return _c.mutation
}

// Save creates the QuizQuestion in the database.
func (_c *QuizQuestionCreate) Save(ctx context.Context) (*QuizQuestion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuizQuestionCreate) SaveX(ctx context.Context) *QuizQuestion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuizQuestionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuizQuestionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuizQuestionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quizquestion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := quizquestion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuizQuestionCreate) check() error {
	if _, ok := _c.mutation.QuestionText(); !ok {
		return &ValidationError{Name: "question_text", err: errors.New(`ent: missing required field "QuizQuestion.question_text"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuizQuestion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QuizQuestion.updated_at"`)}
	}
	if len(_c.mutation.QuizIDs()) == 0 {
		return &ValidationError{Name: "quiz", err: errors.New(`ent: missing required edge "QuizQuestion.quiz"`)}
	}
	return nil
}

func (_c *QuizQuestionCreate) sqlSave(ctx context.Context) (*QuizQuestion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected QuizQuestion.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuizQuestionCreate) createSpec() (*QuizQuestion, *sqlgraph.CreateSpec) {
	var (
		_node = &QuizQuestion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quizquestion.Table, sqlgraph.NewFieldSpec(quizquestion.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.QuestionText(); ok {
		_spec.SetField(quizquestion.FieldQuestionText, field.TypeString, value)
		_node.QuestionText = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quizquestion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(quizquestion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.QuizIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quizquestion.QuizTable,
			Columns: []string{quizquestion.QuizColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.quiz_questions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizquestion.AnswersTable,
			Columns: []string{quizquestion.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizanswer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserAnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quizquestion.UserAnswersTable,
			Columns: []string{quizquestion.UserAnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quizuseranswer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuizQuestionCreateBulk is the builder for creating many QuizQuestion entities in bulk.
type QuizQuestionCreateBulk struct {
	config
	err      error
	builders []*QuizQuestionCreate
}

// Save creates the QuizQuestion entities in the database.
func (_c *QuizQuestionCreateBulk) Save(ctx context.Context) ([]*QuizQuestion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QuizQuestion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuizQuestionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuizQuestionCreateBulk) SaveX(ctx context.Context) []*QuizQuestion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuizQuestionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuizQuestionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
