// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/quote"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Quote is the model entity for the Quote schema.
type Quote struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// GuildID holds the value of the "guild_id" field.
	GuildID string `json:"guild_id,omitempty"`
	// AuthorID holds the value of the "author_id" field.
	AuthorID string `json:"author_id,omitempty"`
	// Quote holds the value of the "quote" field.
	Quote string `json:"quote,omitempty"`
	// Context holds the value of the "context" field.
	Context string `json:"context,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Quote) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quote.FieldID, quote.FieldGuildID, quote.FieldAuthorID, quote.FieldQuote, quote.FieldContext:
			values[i] = new(sql.NullString)
		case quote.FieldCreatedAt, quote.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Quote fields.
func (_m *Quote) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quote.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case quote.FieldGuildID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guild_id", values[i])
			} else if value.Valid {
				_m.GuildID = value.String
			}
		case quote.FieldAuthorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author_id", values[i])
			} else if value.Valid {
				_m.AuthorID = value.String
			}
		case quote.FieldQuote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quote", values[i])
			} else if value.Valid {
				_m.Quote = value.String
			}
		case quote.FieldContext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context", values[i])
			} else if value.Valid {
				_m.Context = value.String
			}
		case quote.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case quote.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Quote.
// This includes values selected through modifiers, order, etc.
func (_m *Quote) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Quote.
// Note that you need to call Quote.Unwrap() before calling this method if this Quote
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Quote) Update() *QuoteUpdateOne {
	return NewQuoteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Quote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Quote) Unwrap() *Quote {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Quote is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Quote) String() string {
	var builder strings.Builder
	builder.WriteString("Quote(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("guild_id=")
	builder.WriteString(_m.GuildID)
	builder.WriteString(", ")
	builder.WriteString("author_id=")
	builder.WriteString(_m.AuthorID)
	builder.WriteString(", ")
	builder.WriteString("quote=")
	builder.WriteString(_m.Quote)
	builder.WriteString(", ")
	builder.WriteString("context=")
	builder.WriteString(_m.Context)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Quotes is a parsable slice of Quote.
type Quotes []*Quote
