// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/quote"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuoteCreate is the builder for creating a Quote entity.
type QuoteCreate struct {
	config
	mutation *QuoteMutation
	hooks    []Hook
}

// SetGuildID sets the "guild_id" field.
func (_c *QuoteCreate) SetGuildID(v string) *QuoteCreate {
	_c.mutation.SetGuildID(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *QuoteCreate) SetAuthorID(v string) *QuoteCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetQuote sets the "quote" field.
func (_c *QuoteCreate) SetQuote(v string) *QuoteCreate {
	_c.mutation.SetQuote(v)
	return _c
}

// SetContext sets the "context" field.
func (_c *QuoteCreate) SetContext(v string) *QuoteCreate {
	_c.mutation.SetContext(v)
	return _c
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (_c *QuoteCreate) SetNillableContext(v *string) *QuoteCreate {
	if v != nil {
		_c.SetContext(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuoteCreate) SetCreatedAt(v time.Time) *QuoteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuoteCreate) SetNillableCreatedAt(v *time.Time) *QuoteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuoteCreate) SetUpdatedAt(v time.Time) *QuoteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuoteCreate) SetNillableUpdatedAt(v *time.Time) *QuoteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuoteCreate) SetID(v string) *QuoteCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the QuoteMutation object of the builder.
func (_c *QuoteCreate) Mutation() *QuoteMutation {
	return _c.mutation
}

// Save creates the Quote in the database.
func (_c *QuoteCreate) Save(ctx context.Context) (*Quote, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuoteCreate) SaveX(ctx context.Context) *Quote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuoteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuoteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuoteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quote.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := quote.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuoteCreate) check() error {
	if _, ok := _c.mutation.GuildID(); !ok {
		return &ValidationError{Name: "guild_id", err: errors.New(`ent: missing required field "Quote.guild_id"`)}
	}
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "Quote.author_id"`)}
	}
	if _, ok := _c.mutation.Quote(); !ok {
		return &ValidationError{Name: "quote", err: errors.New(`ent: missing required field "Quote.quote"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Quote.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Quote.updated_at"`)}
	}
	return nil
}

func (_c *QuoteCreate) sqlSave(ctx context.Context) (*Quote, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Quote.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuoteCreate) createSpec() (*Quote, *sqlgraph.CreateSpec) {
	var (
		_node = &Quote{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quote.Table, sqlgraph.NewFieldSpec(quote.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GuildID(); ok {
		_spec.SetField(quote.FieldGuildID, field.TypeString, value)
		_node.GuildID = value
	}
	if value, ok := _c.mutation.AuthorID(); ok {
		_spec.SetField(quote.FieldAuthorID, field.TypeString, value)
		_node.AuthorID = value
	}
	if value, ok := _c.mutation.Quote(); ok {
		_spec.SetField(quote.FieldQuote, field.TypeString, value)
		_node.Quote = value
	}
	if value, ok := _c.mutation.Context(); ok {
		_spec.SetField(quote.FieldContext, field.TypeString, value)
		_node.Context = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quote.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(quote.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// QuoteCreateBulk is the builder for creating many Quote entities in bulk.
type QuoteCreateBulk struct {
	config
	err      error
	builders []*QuoteCreate
}

// Save creates the Quote entities in the database.
func (_c *QuoteCreateBulk) Save(ctx context.Context) ([]*Quote, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Quote, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuoteCreateBulk) SaveX(ctx context.Context) []*Quote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuoteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuoteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
