// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/birthday"
	"Eve/internal/database/ent/guildconfig"
	"Eve/internal/database/ent/quote"
	"Eve/internal/database/tables"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	birthdayFields := tables.Birthday{}.Fields()
	_ = birthdayFields
	// birthdayDescCreatedAt is the schema descriptor for created_at field.
	birthdayDescCreatedAt := birthdayFields[2].Descriptor()
	// birthday.DefaultCreatedAt holds the default value on creation for the created_at field.
	birthday.DefaultCreatedAt = birthdayDescCreatedAt.Default.(func() time.Time)
	// birthdayDescUpdatedAt is the schema descriptor for updated_at field.
	birthdayDescUpdatedAt := birthdayFields[3].Descriptor()
	// birthday.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	birthday.DefaultUpdatedAt = birthdayDescUpdatedAt.Default.(func() time.Time)
	// birthday.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	birthday.UpdateDefaultUpdatedAt = birthdayDescUpdatedAt.UpdateDefault.(func() time.Time)
	guildconfigFields := tables.GuildConfig{}.Fields()
	_ = guildconfigFields
	// guildconfigDescCreatedAt is the schema descriptor for created_at field.
	guildconfigDescCreatedAt := guildconfigFields[3].Descriptor()
	// guildconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	guildconfig.DefaultCreatedAt = guildconfigDescCreatedAt.Default.(func() time.Time)
	// guildconfigDescUpdatedAt is the schema descriptor for updated_at field.
	guildconfigDescUpdatedAt := guildconfigFields[4].Descriptor()
	// guildconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	guildconfig.DefaultUpdatedAt = guildconfigDescUpdatedAt.Default.(func() time.Time)
	// guildconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	guildconfig.UpdateDefaultUpdatedAt = guildconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	quoteFields := tables.Quote{}.Fields()
	_ = quoteFields
	// quoteDescCreatedAt is the schema descriptor for created_at field.
	quoteDescCreatedAt := quoteFields[5].Descriptor()
	// quote.DefaultCreatedAt holds the default value on creation for the created_at field.
	quote.DefaultCreatedAt = quoteDescCreatedAt.Default.(func() time.Time)
	// quoteDescUpdatedAt is the schema descriptor for updated_at field.
	quoteDescUpdatedAt := quoteFields[6].Descriptor()
	// quote.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	quote.DefaultUpdatedAt = quoteDescUpdatedAt.Default.(func() time.Time)
	// quote.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	quote.UpdateDefaultUpdatedAt = quoteDescUpdatedAt.UpdateDefault.(func() time.Time)
}
