// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/birthday"
	"Eve/internal/database/ent/guildconfig"
	"Eve/internal/database/ent/quiz"
	"Eve/internal/database/ent/quizanswer"
	"Eve/internal/database/ent/quizquestion"
	"Eve/internal/database/ent/quizuseranswer"
	"Eve/internal/database/ent/quote"
	"Eve/internal/database/tables"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	birthdayFields := tables.Birthday{}.Fields()
	_ = birthdayFields
	// birthdayDescCreatedAt is the schema descriptor for created_at field.
	birthdayDescCreatedAt := birthdayFields[2].Descriptor()
	// birthday.DefaultCreatedAt holds the default value on creation for the created_at field.
	birthday.DefaultCreatedAt = birthdayDescCreatedAt.Default.(func() time.Time)
	// birthdayDescUpdatedAt is the schema descriptor for updated_at field.
	birthdayDescUpdatedAt := birthdayFields[3].Descriptor()
	// birthday.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	birthday.DefaultUpdatedAt = birthdayDescUpdatedAt.Default.(func() time.Time)
	// birthday.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	birthday.UpdateDefaultUpdatedAt = birthdayDescUpdatedAt.UpdateDefault.(func() time.Time)
	guildconfigFields := tables.GuildConfig{}.Fields()
	_ = guildconfigFields
	// guildconfigDescCreatedAt is the schema descriptor for created_at field.
	guildconfigDescCreatedAt := guildconfigFields[3].Descriptor()
	// guildconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	guildconfig.DefaultCreatedAt = guildconfigDescCreatedAt.Default.(func() time.Time)
	// guildconfigDescUpdatedAt is the schema descriptor for updated_at field.
	guildconfigDescUpdatedAt := guildconfigFields[4].Descriptor()
	// guildconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	guildconfig.DefaultUpdatedAt = guildconfigDescUpdatedAt.Default.(func() time.Time)
	// guildconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	guildconfig.UpdateDefaultUpdatedAt = guildconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	quizFields := tables.Quiz{}.Fields()
	_ = quizFields
	// quizDescCreatedAt is the schema descriptor for created_at field.
	quizDescCreatedAt := quizFields[3].Descriptor()
	// quiz.DefaultCreatedAt holds the default value on creation for the created_at field.
	quiz.DefaultCreatedAt = quizDescCreatedAt.Default.(func() time.Time)
	// quizDescUpdatedAt is the schema descriptor for updated_at field.
	quizDescUpdatedAt := quizFields[4].Descriptor()
	// quiz.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	quiz.DefaultUpdatedAt = quizDescUpdatedAt.Default.(func() time.Time)
	// quiz.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	quiz.UpdateDefaultUpdatedAt = quizDescUpdatedAt.UpdateDefault.(func() time.Time)
	quizanswerFields := tables.QuizAnswer{}.Fields()
	_ = quizanswerFields
	// quizanswerDescIsValid is the schema descriptor for is_valid field.
	quizanswerDescIsValid := quizanswerFields[2].Descriptor()
	// quizanswer.DefaultIsValid holds the default value on creation for the is_valid field.
	quizanswer.DefaultIsValid = quizanswerDescIsValid.Default.(bool)
	// quizanswerDescCreatedAt is the schema descriptor for created_at field.
	quizanswerDescCreatedAt := quizanswerFields[3].Descriptor()
	// quizanswer.DefaultCreatedAt holds the default value on creation for the created_at field.
	quizanswer.DefaultCreatedAt = quizanswerDescCreatedAt.Default.(func() time.Time)
	// quizanswerDescUpdatedAt is the schema descriptor for updated_at field.
	quizanswerDescUpdatedAt := quizanswerFields[4].Descriptor()
	// quizanswer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	quizanswer.DefaultUpdatedAt = quizanswerDescUpdatedAt.Default.(func() time.Time)
	// quizanswer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	quizanswer.UpdateDefaultUpdatedAt = quizanswerDescUpdatedAt.UpdateDefault.(func() time.Time)
	quizquestionFields := tables.QuizQuestion{}.Fields()
	_ = quizquestionFields
	// quizquestionDescCreatedAt is the schema descriptor for created_at field.
	quizquestionDescCreatedAt := quizquestionFields[2].Descriptor()
	// quizquestion.DefaultCreatedAt holds the default value on creation for the created_at field.
	quizquestion.DefaultCreatedAt = quizquestionDescCreatedAt.Default.(func() time.Time)
	// quizquestionDescUpdatedAt is the schema descriptor for updated_at field.
	quizquestionDescUpdatedAt := quizquestionFields[3].Descriptor()
	// quizquestion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	quizquestion.DefaultUpdatedAt = quizquestionDescUpdatedAt.Default.(func() time.Time)
	// quizquestion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	quizquestion.UpdateDefaultUpdatedAt = quizquestionDescUpdatedAt.UpdateDefault.(func() time.Time)
	quizuseranswerFields := tables.QuizUserAnswer{}.Fields()
	_ = quizuseranswerFields
	// quizuseranswerDescAnsweredAt is the schema descriptor for answered_at field.
	quizuseranswerDescAnsweredAt := quizuseranswerFields[2].Descriptor()
	// quizuseranswer.DefaultAnsweredAt holds the default value on creation for the answered_at field.
	quizuseranswer.DefaultAnsweredAt = quizuseranswerDescAnsweredAt.Default.(func() time.Time)
	quoteFields := tables.Quote{}.Fields()
	_ = quoteFields
	// quoteDescCreatedAt is the schema descriptor for created_at field.
	quoteDescCreatedAt := quoteFields[5].Descriptor()
	// quote.DefaultCreatedAt holds the default value on creation for the created_at field.
	quote.DefaultCreatedAt = quoteDescCreatedAt.Default.(func() time.Time)
	// quoteDescUpdatedAt is the schema descriptor for updated_at field.
	quoteDescUpdatedAt := quoteFields[6].Descriptor()
	// quote.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	quote.DefaultUpdatedAt = quoteDescUpdatedAt.Default.(func() time.Time)
	// quote.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	quote.UpdateDefaultUpdatedAt = quoteDescUpdatedAt.UpdateDefault.(func() time.Time)
}
