// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Eve/internal/database/ent/predicate"
	"Eve/internal/database/ent/stream"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StreamUpdate is the builder for updating Stream entities.
type StreamUpdate struct {
	config
	hooks    []Hook
	mutation *StreamMutation
}

// Where appends a list predicates to the StreamUpdate builder.
func (_u *StreamUpdate) Where(ps ...predicate.Stream) *StreamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *StreamUpdate) SetGuildID(v string) *StreamUpdate {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *StreamUpdate) SetNillableGuildID(v *string) *StreamUpdate {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *StreamUpdate) SetChannelID(v string) *StreamUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *StreamUpdate) SetNillableChannelID(v *string) *StreamUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *StreamUpdate) SetRoleID(v string) *StreamUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *StreamUpdate) SetNillableRoleID(v *string) *StreamUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// ClearRoleID clears the value of the "role_id" field.
func (_u *StreamUpdate) ClearRoleID() *StreamUpdate {
	_u.mutation.ClearRoleID()
	return _u
}

// SetTwitchUserID sets the "twitch_user_id" field.
func (_u *StreamUpdate) SetTwitchUserID(v string) *StreamUpdate {
	_u.mutation.SetTwitchUserID(v)
	return _u
}

// SetNillableTwitchUserID sets the "twitch_user_id" field if the given value is not nil.
func (_u *StreamUpdate) SetNillableTwitchUserID(v *string) *StreamUpdate {
	if v != nil {
		_u.SetTwitchUserID(*v)
	}
	return _u
}

// SetTwitchLogin sets the "twitch_login" field.
func (_u *StreamUpdate) SetTwitchLogin(v string) *StreamUpdate {
	_u.mutation.SetTwitchLogin(v)
	return _u
}

// SetNillableTwitchLogin sets the "twitch_login" field if the given value is not nil.
func (_u *StreamUpdate) SetNillableTwitchLogin(v *string) *StreamUpdate {
	if v != nil {
		_u.SetTwitchLogin(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *StreamUpdate) SetMessageID(v string) *StreamUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *StreamUpdate) SetNillableMessageID(v *string) *StreamUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// ClearMessageID clears the value of the "message_id" field.
func (_u *StreamUpdate) ClearMessageID() *StreamUpdate {
	_u.mutation.ClearMessageID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StreamUpdate) SetUpdatedAt(v time.Time) *StreamUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StreamMutation object of the builder.
func (_u *StreamUpdate) Mutation() *StreamMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StreamUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StreamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StreamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StreamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StreamUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := stream.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *StreamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(stream.Table, stream.Columns, sqlgraph.NewFieldSpec(stream.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(stream.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(stream.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(stream.FieldRoleID, field.TypeString, value)
	}
	if _u.mutation.RoleIDCleared() {
		_spec.ClearField(stream.FieldRoleID, field.TypeString)
	}
	if value, ok := _u.mutation.TwitchUserID(); ok {
		_spec.SetField(stream.FieldTwitchUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TwitchLogin(); ok {
		_spec.SetField(stream.FieldTwitchLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(stream.FieldMessageID, field.TypeString, value)
	}
	if _u.mutation.MessageIDCleared() {
		_spec.ClearField(stream.FieldMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(stream.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StreamUpdateOne is the builder for updating a single Stream entity.
type StreamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StreamMutation
}

// SetGuildID sets the "guild_id" field.
func (_u *StreamUpdateOne) SetGuildID(v string) *StreamUpdateOne {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *StreamUpdateOne) SetNillableGuildID(v *string) *StreamUpdateOne {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *StreamUpdateOne) SetChannelID(v string) *StreamUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *StreamUpdateOne) SetNillableChannelID(v *string) *StreamUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *StreamUpdateOne) SetRoleID(v string) *StreamUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *StreamUpdateOne) SetNillableRoleID(v *string) *StreamUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// ClearRoleID clears the value of the "role_id" field.
func (_u *StreamUpdateOne) ClearRoleID() *StreamUpdateOne {
	_u.mutation.ClearRoleID()
	return _u
}

// SetTwitchUserID sets the "twitch_user_id" field.
func (_u *StreamUpdateOne) SetTwitchUserID(v string) *StreamUpdateOne {
	_u.mutation.SetTwitchUserID(v)
	return _u
}

// SetNillableTwitchUserID sets the "twitch_user_id" field if the given value is not nil.
func (_u *StreamUpdateOne) SetNillableTwitchUserID(v *string) *StreamUpdateOne {
	if v != nil {
		_u.SetTwitchUserID(*v)
	}
	return _u
}

// SetTwitchLogin sets the "twitch_login" field.
func (_u *StreamUpdateOne) SetTwitchLogin(v string) *StreamUpdateOne {
	_u.mutation.SetTwitchLogin(v)
	return _u
}

// SetNillableTwitchLogin sets the "twitch_login" field if the given value is not nil.
func (_u *StreamUpdateOne) SetNillableTwitchLogin(v *string) *StreamUpdateOne {
	if v != nil {
		_u.SetTwitchLogin(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *StreamUpdateOne) SetMessageID(v string) *StreamUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *StreamUpdateOne) SetNillableMessageID(v *string) *StreamUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// ClearMessageID clears the value of the "message_id" field.
func (_u *StreamUpdateOne) ClearMessageID() *StreamUpdateOne {
	_u.mutation.ClearMessageID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StreamUpdateOne) SetUpdatedAt(v time.Time) *StreamUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StreamMutation object of the builder.
func (_u *StreamUpdateOne) Mutation() *StreamMutation {
	return _u.mutation
}

// Where appends a list predicates to the StreamUpdate builder.
func (_u *StreamUpdateOne) Where(ps ...predicate.Stream) *StreamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StreamUpdateOne) Select(field string, fields ...string) *StreamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Stream entity.
func (_u *StreamUpdateOne) Save(ctx context.Context) (*Stream, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StreamUpdateOne) SaveX(ctx context.Context) *Stream {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StreamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StreamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StreamUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := stream.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *StreamUpdateOne) sqlSave(ctx context.Context) (_node *Stream, err error) {
	_spec := sqlgraph.NewUpdateSpec(stream.Table, stream.Columns, sqlgraph.NewFieldSpec(stream.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Stream.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stream.FieldID)
		for _, f := range fields {
			if !stream.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stream.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(stream.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(stream.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(stream.FieldRoleID, field.TypeString, value)
	}
	if _u.mutation.RoleIDCleared() {
		_spec.ClearField(stream.FieldRoleID, field.TypeString)
	}
	if value, ok := _u.mutation.TwitchUserID(); ok {
		_spec.SetField(stream.FieldTwitchUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TwitchLogin(); ok {
		_spec.SetField(stream.FieldTwitchLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(stream.FieldMessageID, field.TypeString, value)
	}
	if _u.mutation.MessageIDCleared() {
		_spec.ClearField(stream.FieldMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(stream.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Stream{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
