// Code generated by ent, DO NOT EDIT.

package lotoplayer

import (
	"Eve/internal/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldContainsFold(FieldID, id))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldGameID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldName, v))
}

// LastPlay applies equality check predicate on the "last_play" field. It's identical to LastPlayEQ.
func LastPlay(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldLastPlay, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldUpdatedAt, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNotIn(FieldGameID, vs...))
}

// GameIDGT applies the GT predicate on the "game_id" field.
func GameIDGT(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGT(FieldGameID, v))
}

// GameIDGTE applies the GTE predicate on the "game_id" field.
func GameIDGTE(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGTE(FieldGameID, v))
}

// GameIDLT applies the LT predicate on the "game_id" field.
func GameIDLT(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLT(FieldGameID, v))
}

// GameIDLTE applies the LTE predicate on the "game_id" field.
func GameIDLTE(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLTE(FieldGameID, v))
}

// GameIDContains applies the Contains predicate on the "game_id" field.
func GameIDContains(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldContains(FieldGameID, v))
}

// GameIDHasPrefix applies the HasPrefix predicate on the "game_id" field.
func GameIDHasPrefix(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldHasPrefix(FieldGameID, v))
}

// GameIDHasSuffix applies the HasSuffix predicate on the "game_id" field.
func GameIDHasSuffix(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldHasSuffix(FieldGameID, v))
}

// GameIDEqualFold applies the EqualFold predicate on the "game_id" field.
func GameIDEqualFold(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEqualFold(FieldGameID, v))
}

// GameIDContainsFold applies the ContainsFold predicate on the "game_id" field.
func GameIDContainsFold(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldContainsFold(FieldGameID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldContainsFold(FieldName, v))
}

// LastPlayEQ applies the EQ predicate on the "last_play" field.
func LastPlayEQ(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldLastPlay, v))
}

// LastPlayNEQ applies the NEQ predicate on the "last_play" field.
func LastPlayNEQ(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNEQ(FieldLastPlay, v))
}

// LastPlayIn applies the In predicate on the "last_play" field.
func LastPlayIn(vs ...time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldIn(FieldLastPlay, vs...))
}

// LastPlayNotIn applies the NotIn predicate on the "last_play" field.
func LastPlayNotIn(vs ...time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNotIn(FieldLastPlay, vs...))
}

// LastPlayGT applies the GT predicate on the "last_play" field.
func LastPlayGT(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGT(FieldLastPlay, v))
}

// LastPlayGTE applies the GTE predicate on the "last_play" field.
func LastPlayGTE(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGTE(FieldLastPlay, v))
}

// LastPlayLT applies the LT predicate on the "last_play" field.
func LastPlayLT(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLT(FieldLastPlay, v))
}

// LastPlayLTE applies the LTE predicate on the "last_play" field.
func LastPlayLTE(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLTE(FieldLastPlay, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGame applies the HasEdge predicate on the "game" edge.
func HasGame() predicate.LotoPlayer {
	return predicate.LotoPlayer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GameTable, GameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameWith applies the HasEdge predicate on the "game" edge with a given conditions (other predicates).
func HasGameWith(preds ...predicate.LotoGame) predicate.LotoPlayer {
	return predicate.LotoPlayer(func(s *sql.Selector) {
		step := newGameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTickets applies the HasEdge predicate on the "tickets" edge.
func HasTickets() predicate.LotoPlayer {
	return predicate.LotoPlayer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TicketsTable, TicketsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketsWith applies the HasEdge predicate on the "tickets" edge with a given conditions (other predicates).
func HasTicketsWith(preds ...predicate.LotoTicket) predicate.LotoPlayer {
	return predicate.LotoPlayer(func(s *sql.Selector) {
		step := newTicketsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWonPrizes applies the HasEdge predicate on the "won_prizes" edge.
func HasWonPrizes() predicate.LotoPlayer {
	return predicate.LotoPlayer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WonPrizesTable, WonPrizesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWonPrizesWith applies the HasEdge predicate on the "won_prizes" edge with a given conditions (other predicates).
func HasWonPrizesWith(preds ...predicate.LotoPrize) predicate.LotoPlayer {
	return predicate.LotoPlayer(func(s *sql.Selector) {
		step := newWonPrizesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotoPlayer) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotoPlayer) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotoPlayer) predicate.LotoPlayer {
	return predicate.LotoPlayer(sql.NotPredicates(p))
}
