// Code generated by ent, DO NOT EDIT.

package stream

import (
	"Eve/internal/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldID, id))
}

// GuildID applies equality check predicate on the "guild_id" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldGuildID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldChannelID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldRoleID, v))
}

// TwitchUserID applies equality check predicate on the "twitch_user_id" field. It's identical to TwitchUserIDEQ.
func TwitchUserID(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldTwitchUserID, v))
}

// TwitchLogin applies equality check predicate on the "twitch_login" field. It's identical to TwitchLoginEQ.
func TwitchLogin(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldTwitchLogin, v))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldMessageID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldUpdatedAt, v))
}

// GuildIDEQ applies the EQ predicate on the "guild_id" field.
func GuildIDEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guild_id" field.
func GuildIDNEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guild_id" field.
func GuildIDIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guild_id" field.
func GuildIDNotIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guild_id" field.
func GuildIDGT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guild_id" field.
func GuildIDGTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guild_id" field.
func GuildIDLT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guild_id" field.
func GuildIDLTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDContains applies the Contains predicate on the "guild_id" field.
func GuildIDContains(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContains(FieldGuildID, v))
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guild_id" field.
func GuildIDHasPrefix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasPrefix(FieldGuildID, v))
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guild_id" field.
func GuildIDHasSuffix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasSuffix(FieldGuildID, v))
}

// GuildIDEqualFold applies the EqualFold predicate on the "guild_id" field.
func GuildIDEqualFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEqualFold(FieldGuildID, v))
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guild_id" field.
func GuildIDContainsFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContainsFold(FieldGuildID, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDContains applies the Contains predicate on the "channel_id" field.
func ChannelIDContains(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContains(FieldChannelID, v))
}

// ChannelIDHasPrefix applies the HasPrefix predicate on the "channel_id" field.
func ChannelIDHasPrefix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasPrefix(FieldChannelID, v))
}

// ChannelIDHasSuffix applies the HasSuffix predicate on the "channel_id" field.
func ChannelIDHasSuffix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasSuffix(FieldChannelID, v))
}

// ChannelIDEqualFold applies the EqualFold predicate on the "channel_id" field.
func ChannelIDEqualFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEqualFold(FieldChannelID, v))
}

// ChannelIDContainsFold applies the ContainsFold predicate on the "channel_id" field.
func ChannelIDContainsFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContainsFold(FieldChannelID, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldRoleID, v))
}

// RoleIDContains applies the Contains predicate on the "role_id" field.
func RoleIDContains(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContains(FieldRoleID, v))
}

// RoleIDHasPrefix applies the HasPrefix predicate on the "role_id" field.
func RoleIDHasPrefix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasPrefix(FieldRoleID, v))
}

// RoleIDHasSuffix applies the HasSuffix predicate on the "role_id" field.
func RoleIDHasSuffix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasSuffix(FieldRoleID, v))
}

// RoleIDIsNil applies the IsNil predicate on the "role_id" field.
func RoleIDIsNil() predicate.Stream {
	return predicate.Stream(sql.FieldIsNull(FieldRoleID))
}

// RoleIDNotNil applies the NotNil predicate on the "role_id" field.
func RoleIDNotNil() predicate.Stream {
	return predicate.Stream(sql.FieldNotNull(FieldRoleID))
}

// RoleIDEqualFold applies the EqualFold predicate on the "role_id" field.
func RoleIDEqualFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEqualFold(FieldRoleID, v))
}

// RoleIDContainsFold applies the ContainsFold predicate on the "role_id" field.
func RoleIDContainsFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContainsFold(FieldRoleID, v))
}

// TwitchUserIDEQ applies the EQ predicate on the "twitch_user_id" field.
func TwitchUserIDEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldTwitchUserID, v))
}

// TwitchUserIDNEQ applies the NEQ predicate on the "twitch_user_id" field.
func TwitchUserIDNEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldTwitchUserID, v))
}

// TwitchUserIDIn applies the In predicate on the "twitch_user_id" field.
func TwitchUserIDIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldTwitchUserID, vs...))
}

// TwitchUserIDNotIn applies the NotIn predicate on the "twitch_user_id" field.
func TwitchUserIDNotIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldTwitchUserID, vs...))
}

// TwitchUserIDGT applies the GT predicate on the "twitch_user_id" field.
func TwitchUserIDGT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldTwitchUserID, v))
}

// TwitchUserIDGTE applies the GTE predicate on the "twitch_user_id" field.
func TwitchUserIDGTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldTwitchUserID, v))
}

// TwitchUserIDLT applies the LT predicate on the "twitch_user_id" field.
func TwitchUserIDLT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldTwitchUserID, v))
}

// TwitchUserIDLTE applies the LTE predicate on the "twitch_user_id" field.
func TwitchUserIDLTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldTwitchUserID, v))
}

// TwitchUserIDContains applies the Contains predicate on the "twitch_user_id" field.
func TwitchUserIDContains(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContains(FieldTwitchUserID, v))
}

// TwitchUserIDHasPrefix applies the HasPrefix predicate on the "twitch_user_id" field.
func TwitchUserIDHasPrefix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasPrefix(FieldTwitchUserID, v))
}

// TwitchUserIDHasSuffix applies the HasSuffix predicate on the "twitch_user_id" field.
func TwitchUserIDHasSuffix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasSuffix(FieldTwitchUserID, v))
}

// TwitchUserIDEqualFold applies the EqualFold predicate on the "twitch_user_id" field.
func TwitchUserIDEqualFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEqualFold(FieldTwitchUserID, v))
}

// TwitchUserIDContainsFold applies the ContainsFold predicate on the "twitch_user_id" field.
func TwitchUserIDContainsFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContainsFold(FieldTwitchUserID, v))
}

// TwitchLoginEQ applies the EQ predicate on the "twitch_login" field.
func TwitchLoginEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldTwitchLogin, v))
}

// TwitchLoginNEQ applies the NEQ predicate on the "twitch_login" field.
func TwitchLoginNEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldTwitchLogin, v))
}

// TwitchLoginIn applies the In predicate on the "twitch_login" field.
func TwitchLoginIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldTwitchLogin, vs...))
}

// TwitchLoginNotIn applies the NotIn predicate on the "twitch_login" field.
func TwitchLoginNotIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldTwitchLogin, vs...))
}

// TwitchLoginGT applies the GT predicate on the "twitch_login" field.
func TwitchLoginGT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldTwitchLogin, v))
}

// TwitchLoginGTE applies the GTE predicate on the "twitch_login" field.
func TwitchLoginGTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldTwitchLogin, v))
}

// TwitchLoginLT applies the LT predicate on the "twitch_login" field.
func TwitchLoginLT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldTwitchLogin, v))
}

// TwitchLoginLTE applies the LTE predicate on the "twitch_login" field.
func TwitchLoginLTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldTwitchLogin, v))
}

// TwitchLoginContains applies the Contains predicate on the "twitch_login" field.
func TwitchLoginContains(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContains(FieldTwitchLogin, v))
}

// TwitchLoginHasPrefix applies the HasPrefix predicate on the "twitch_login" field.
func TwitchLoginHasPrefix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasPrefix(FieldTwitchLogin, v))
}

// TwitchLoginHasSuffix applies the HasSuffix predicate on the "twitch_login" field.
func TwitchLoginHasSuffix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasSuffix(FieldTwitchLogin, v))
}

// TwitchLoginEqualFold applies the EqualFold predicate on the "twitch_login" field.
func TwitchLoginEqualFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEqualFold(FieldTwitchLogin, v))
}

// TwitchLoginContainsFold applies the ContainsFold predicate on the "twitch_login" field.
func TwitchLoginContainsFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContainsFold(FieldTwitchLogin, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.Stream {
	return predicate.Stream(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDIsNil applies the IsNil predicate on the "message_id" field.
func MessageIDIsNil() predicate.Stream {
	return predicate.Stream(sql.FieldIsNull(FieldMessageID))
}

// MessageIDNotNil applies the NotNil predicate on the "message_id" field.
func MessageIDNotNil() predicate.Stream {
	return predicate.Stream(sql.FieldNotNull(FieldMessageID))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.Stream {
	return predicate.Stream(sql.FieldContainsFold(FieldMessageID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Stream {
	return predicate.Stream(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Stream) predicate.Stream {
	return predicate.Stream(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Stream) predicate.Stream {
	return predicate.Stream(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Stream) predicate.Stream {
	return predicate.Stream(sql.NotPredicates(p))
}
