// Code generated by ent, DO NOT EDIT.

package mpthread

import (
	"Eve/internal/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MPThread {
	return predicate.MPThread(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MPThread {
	return predicate.MPThread(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MPThread {
	return predicate.MPThread(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MPThread {
	return predicate.MPThread(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MPThread {
	return predicate.MPThread(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MPThread {
	return predicate.MPThread(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MPThread {
	return predicate.MPThread(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MPThread {
	return predicate.MPThread(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MPThread {
	return predicate.MPThread(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldEQ(FieldUserID, v))
}

// ThreadID applies equality check predicate on the "thread_id" field. It's identical to ThreadIDEQ.
func ThreadID(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldEQ(FieldThreadID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MPThread {
	return predicate.MPThread(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.MPThread {
	return predicate.MPThread(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.MPThread {
	return predicate.MPThread(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldContainsFold(FieldUserID, v))
}

// ThreadIDEQ applies the EQ predicate on the "thread_id" field.
func ThreadIDEQ(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldEQ(FieldThreadID, v))
}

// ThreadIDNEQ applies the NEQ predicate on the "thread_id" field.
func ThreadIDNEQ(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldNEQ(FieldThreadID, v))
}

// ThreadIDIn applies the In predicate on the "thread_id" field.
func ThreadIDIn(vs ...string) predicate.MPThread {
	return predicate.MPThread(sql.FieldIn(FieldThreadID, vs...))
}

// ThreadIDNotIn applies the NotIn predicate on the "thread_id" field.
func ThreadIDNotIn(vs ...string) predicate.MPThread {
	return predicate.MPThread(sql.FieldNotIn(FieldThreadID, vs...))
}

// ThreadIDGT applies the GT predicate on the "thread_id" field.
func ThreadIDGT(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldGT(FieldThreadID, v))
}

// ThreadIDGTE applies the GTE predicate on the "thread_id" field.
func ThreadIDGTE(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldGTE(FieldThreadID, v))
}

// ThreadIDLT applies the LT predicate on the "thread_id" field.
func ThreadIDLT(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldLT(FieldThreadID, v))
}

// ThreadIDLTE applies the LTE predicate on the "thread_id" field.
func ThreadIDLTE(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldLTE(FieldThreadID, v))
}

// ThreadIDContains applies the Contains predicate on the "thread_id" field.
func ThreadIDContains(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldContains(FieldThreadID, v))
}

// ThreadIDHasPrefix applies the HasPrefix predicate on the "thread_id" field.
func ThreadIDHasPrefix(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldHasPrefix(FieldThreadID, v))
}

// ThreadIDHasSuffix applies the HasSuffix predicate on the "thread_id" field.
func ThreadIDHasSuffix(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldHasSuffix(FieldThreadID, v))
}

// ThreadIDEqualFold applies the EqualFold predicate on the "thread_id" field.
func ThreadIDEqualFold(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldEqualFold(FieldThreadID, v))
}

// ThreadIDContainsFold applies the ContainsFold predicate on the "thread_id" field.
func ThreadIDContainsFold(v string) predicate.MPThread {
	return predicate.MPThread(sql.FieldContainsFold(FieldThreadID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MPThread {
	return predicate.MPThread(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MPThread {
	return predicate.MPThread(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MPThread {
	return predicate.MPThread(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MPThread {
	return predicate.MPThread(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MPThread {
	return predicate.MPThread(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MPThread {
	return predicate.MPThread(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MPThread {
	return predicate.MPThread(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MPThread {
	return predicate.MPThread(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MPThread) predicate.MPThread {
	return predicate.MPThread(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MPThread) predicate.MPThread {
	return predicate.MPThread(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MPThread) predicate.MPThread {
	return predicate.MPThread(sql.NotPredicates(p))
}
