// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BirthdaysColumns holds the columns for the "birthdays" table.
	BirthdaysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "discord_id", Type: field.TypeString, Unique: true},
		{Name: "birthday", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BirthdaysTable holds the schema information for the "birthdays" table.
	BirthdaysTable = &schema.Table{
		Name:       "birthdays",
		Columns:    BirthdaysColumns,
		PrimaryKey: []*schema.Column{BirthdaysColumns[0]},
	}
	// GuildConfigsColumns holds the columns for the "guild_configs" table.
	GuildConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GuildConfigsTable holds the schema information for the "guild_configs" table.
	GuildConfigsTable = &schema.Table{
		Name:       "guild_configs",
		Columns:    GuildConfigsColumns,
		PrimaryKey: []*schema.Column{GuildConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "guildconfig_guild_id_key",
				Unique:  true,
				Columns: []*schema.Column{GuildConfigsColumns[1], GuildConfigsColumns[2]},
			},
		},
	}
	// QuotesColumns holds the columns for the "quotes" table.
	QuotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "author_id", Type: field.TypeString},
		{Name: "quote", Type: field.TypeString},
		{Name: "context", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// QuotesTable holds the schema information for the "quotes" table.
	QuotesTable = &schema.Table{
		Name:       "quotes",
		Columns:    QuotesColumns,
		PrimaryKey: []*schema.Column{QuotesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BirthdaysTable,
		GuildConfigsTable,
		QuotesTable,
	}
)

func init() {
}
